package dev.thefoolish.aidao;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.OpenableColumns;
import android.text.InputType;
import android.view.*;
import android.widget.*;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * AIDao v1.0 creation workspace.
 * Brief -> plan -> iterative refinement/knowledge -> source -> inspect/edit -> user-approved GitHub CI -> APK.
 * Credentials are session-only. Imported material is treated as data, never silently executed.
 */
public class AIDaoActivityV5 extends Activity {
    private static final int BG=Color.rgb(18,19,24),HEADER=Color.rgb(22,23,29),PANEL=Color.rgb(29,31,39),ALT=Color.rgb(35,38,48),MUTED=Color.rgb(157,162,178),BLUE=Color.rgb(80,148,255),GREEN=Color.rgb(76,201,144),YELLOW=Color.rgb(235,190,80),RED=Color.rgb(234,98,108),PURPLE=Color.rgb(145,93,255);
    private static final android.graphics.Typeface UI=android.graphics.Typeface.create("sans-serif",0),BOLD=android.graphics.Typeface.create("sans-serif",1),BRAND=android.graphics.Typeface.create("cursive",1);
    private static final int PICK_KNOWLEDGE=401;
    private SharedPreferences prefs; private LinearLayout root,content,bottom; private String project; private int tab=0; private volatile boolean building=false; private String sessionToken="";

    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("aidao_workspace_v4",MODE_PRIVATE);Window w=getWindow();w.setStatusBarColor(BG);w.setNavigationBarColor(Color.rgb(12,13,17));w.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);if(Build.VERSION.SDK_INT>=30)w.setDecorFitsSystemWindows(false);recoverInterruptedState();showProjects();}

    private void recoverInterruptedState(){String ci=prefs.getString("ci_state","");String stage=prefs.getString("stage","");if((ci.contains("Uploading")||ci.contains("Android CI")||ci.contains("Preparing generated branch")||ci.contains("Build running"))&&!"APK READY".equals(stage)){prefs.edit().putString("ci_state","Recovery required · previous build session was interrupted. Re-enter a GitHub token to safely retry; credentials were not stored.").putString("stage","BUILD RECOVERY").apply();}}

    private void shell(String title,String sub){root=col();root.setBackgroundColor(BG);LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(18),dp(28),dp(18),dp(14));h.setBackgroundColor(HEADER);TextView logo=text("A",22,Color.WHITE,true);logo.setTypeface(BRAND);logo.setGravity(Gravity.CENTER);logo.setContentDescription("AIDao logo");logo.setBackground(gradient());h.addView(logo,lp(dp(44),dp(44),0,0,dp(12),0));LinearLayout names=col();TextView tt=text(title,20,Color.WHITE,true);tt.setMaxLines(2);names.addView(tt);names.addView(text(sub,12,MUTED,false));h.addView(names,new LinearLayout.LayoutParams(0,-2,1));TextView online=text("●",16,GREEN,true);online.setContentDescription("AIDao ready");h.addView(online);root.addView(h);ScrollView s=new ScrollView(this);s.setFillViewport(true);content=col();content.setPadding(dp(18),dp(18),dp(18),dp(30));s.addView(content);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));bottom=nav();root.addView(bottom);setContentView(root);insets(h);}
    private void insets(LinearLayout h){if(Build.VERSION.SDK_INT<23)return;root.setOnApplyWindowInsetsListener((v,i)->{int top=i.getSystemWindowInsetTop(),bot=i.getSystemWindowInsetBottom();if(Build.VERSION.SDK_INT>=30){top=i.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout()).top;bot=i.getInsets(WindowInsets.Type.systemBars()).bottom;boolean ime=i.isVisible(WindowInsets.Type.ime());bottom.setVisibility(ime?View.GONE:View.VISIBLE);}h.setPadding(dp(18),top+dp(22),dp(18),dp(14));bottom.setPadding(dp(6),dp(6),dp(6),Math.max(dp(8),bot+dp(6)));return i;});root.requestApplyInsets();}

    private void showProjects(){project=null;shell("AIDao","Developer workspace · v1.0");card("BUILD WITH AIDAO","Describe an Android app, refine it conversationally, add user-shared knowledge, generate a real multi-screen source tree, inspect/edit files, and explicitly authorize GitHub CI when ready.",BLUE);Button n=primary("New Project");n.setOnClickListener(v->newProject());content.addView(n,lp(-1,dp(52),0,dp(12),0,dp(12)));String p=prefs.getString("project_name",null);if(p!=null){View saved=card("Saved project",p+" · "+stateLabel(),GREEN);saved.setOnClickListener(v->{project=p;tab=0;workspace();});saved.setClickable(true);saved.setContentDescription("Open saved project "+p);}}
    private void newProject(){EditText e=new EditText(this);e.setTypeface(UI);e.setHint("Describe what you want in ordinary language. Example: Create an anime app like Mihon with repository-based providers, search, favorites, history, playback and resume progress.");e.setMinLines(6);e.setTextSize(14);new AlertDialog.Builder(this).setTitle("Create Android project").setMessage("AIDao will first create an editable plan. No credentials, publication, installation, spending, or destructive action occurs here.").setView(e).setPositiveButton("Create",(d,w)->{String brief=e.getText().toString().trim();if(brief.isEmpty())return;project=titleFrom(brief);SharedPreferences.Editor ed=prefs.edit();preserveSettingsAndClearProject(ed);ed.putString("project_name",project).putString("brief",brief).putString("stage","BRIEF READY").apply();workspace();}).setNegativeButton("Cancel",null).show();}
    private void preserveSettingsAndClearProject(SharedPreferences.Editor ed){String repo=prefs.getString("repo","IcyKokane/AIDaoPublic");ed.clear().putString("repo",repo);}

    private void workspace(){if(project==null)project=prefs.getString("project_name","Project");shell(project,"Project workspace · "+stateLabel());tabs();if(tab==0)plan();else if(tab==1)tasks();else if(tab==2)files();else if(tab==3)builds();else if(tab==4)knowledge();else github();}
    private void tabs(){HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout r=row();String[] a={"Plan","Tasks","Files","Builds","Knowledge","GitHub"};for(int i=0;i<a.length;i++){final int x=i;TextView t=text(a[i],13,i==tab?Color.WHITE:MUTED,i==tab);t.setGravity(Gravity.CENTER);t.setMinHeight(dp(48));t.setPadding(dp(16),dp(12),dp(16),dp(12));t.setBackground(round(i==tab?Color.rgb(71,78,104):PANEL,12));t.setOnClickListener(v->{tab=x;workspace();});r.addView(t,lp(-2,-2,0,0,dp(8),0));}hs.addView(r);content.addView(hs,lp(-1,-2,0,0,0,dp(20)));}

    private void plan(){heading("Project plan");card("Project brief",prefs.getString("brief",""),BLUE);String ctx=prefs.getString("context","");if(!ctx.isEmpty())card("Refinement context",bounded(ctx,900),PURPLE);String kn=prefs.getString("knowledge_names","");if(!kn.isEmpty())card("Directed knowledge",kn+" · treated as non-executable planning data",GREEN);if(!prefs.contains("requirements")){Button b=primary("Generate Plan & Tasks");b.setOnClickListener(v->generatePlan());content.addView(b,lp(-1,dp(50),0,dp(12),0,dp(8)));}else{label("REQUIREMENTS",BLUE);for(String r:decode(prefs.getString("requirements","")))card("Requirement",r,BLUE);label("ASSUMPTIONS & SAFETY",YELLOW);for(String a:decode(prefs.getString("assumptions","")))card("Assumption",a,YELLOW);}Button refine=secondary("Refine / Modify Project");refine.setOnClickListener(v->refineProject());content.addView(refine,lp(-1,dp(50),0,dp(10),0,0));}
    private void generatePlan(){String context=combinedPlanningContext();ProjectPlanner.Plan p=ProjectPlanner.build(prefs.getString("brief",""),context);SharedPreferences.Editor e=prefs.edit().putString("requirements",encode(p.requirements)).putString("tasks",encode(p.tasks)).putString("assumptions",encode(p.assumptions)).putString("stage","PLAN READY").putBoolean("generated",false).remove("ci_state").remove("run_url").remove("artifact_name");for(int i=0;i<80;i++)e.remove("task_"+i);for(int i=0;i<p.tasks.size();i++)e.putString("task_"+i,TaskExecutionState.PLANNED.name());e.apply();workspace();}
    private String combinedPlanningContext(){String ctx=prefs.getString("context","");String k=prefs.getString("knowledge_text","");return bounded(ctx+"\nDirected knowledge explicitly shared by user:\n"+k,24000);}
    private void refineProject(){EditText e=new EditText(this);e.setTypeface(UI);e.setHint("Example: Add offline downloads, make the home screen focus on Continue Watching, or replace the budget screen with weekly limits.");e.setMinLines(4);new AlertDialog.Builder(this).setTitle("Modify project").setMessage("Describe the change. AIDao will preserve the original brief, add this as project context, and regenerate the plan/source only after you confirm.").setView(e).setPositiveButton("Apply & Replan",(d,w)->{String add=e.getText().toString().trim();if(add.isEmpty())return;String old=prefs.getString("context","");prefs.edit().putString("context",bounded(old+"\nUser refinement: "+add,18000)).remove("requirements").remove("tasks").remove("assumptions").putBoolean("generated",false).putString("stage","REFINEMENT READY").remove("ci_state").remove("run_url").apply();generatePlan();}).setNegativeButton("Cancel",null).show();}

    private void tasks(){heading("Implementation tasks");List<String> ts=decode(prefs.getString("tasks",""));if(ts.isEmpty()){card("No tasks yet","Generate the project plan first.",MUTED);return;}int c=0,a=0,b=0;for(int i=0;i<ts.size();i++){TaskExecutionState s=task(i);if(s==TaskExecutionState.COMPLETE)c++;else if(s==TaskExecutionState.BLOCKED)b++;else if(s==TaskExecutionState.IN_PROGRESS||s==TaskExecutionState.VERIFYING)a++;}card("AIDao execution state",c+" complete · "+a+" active · "+b+" blocked · "+(ts.size()-c-a-b)+" planned",c==ts.size()?GREEN:BLUE);content.addView(text("Task states come from source generation, verification, CI, and bounded repair signals. They are not manual checkboxes.",12,MUTED,false),lp(-1,-2,0,dp(4),0,dp(10)));for(int i=0;i<ts.size();i++){TaskExecutionState s=task(i);card(s.label,ts.get(i),color(s));}}

    private void files(){heading("Generated project files");if(!prefs.getBoolean("generated",false)){card("Source not generated","Open Builds and run source generation after planning.",YELLOW);return;}GeneratedProject g=regenerateWithOverrides();card("Package",g.packageName+" · "+g.files.size()+" files",GREEN);for(GeneratedProject.FileEntry f:g.files){View c=card(f.path,f.taskHint+(hasOverride(f.path)?" · edited by user":""),hasOverride(f.path)?PURPLE:BLUE);c.setClickable(true);c.setOnClickListener(v->inspectFile(f.path));}label("LOCAL VERIFICATION",GREEN);for(String n:g.verificationNotes)card(n.startsWith("PASS")?"Verified":"Problem",n,n.startsWith("PASS")?GREEN:RED);Button reset=secondary("Clear Manual File Overrides");reset.setOnClickListener(v->confirmClearOverrides());content.addView(reset,lp(-1,dp(48),0,dp(10),0,0));}
    private void inspectFile(String path){GeneratedProject g=regenerateWithOverrides();GeneratedProject.FileEntry f=g.find(path);if(f==null)return;LinearLayout box=col();box.setPadding(dp(18),dp(4),dp(18),0);TextView pathView=text(path,12,BLUE,true);box.addView(pathView);EditText src=new EditText(this);src.setTypeface(android.graphics.Typeface.MONOSPACE);src.setText(f.content);src.setTextSize(11);src.setMinLines(14);src.setGravity(Gravity.TOP|Gravity.START);src.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);box.addView(src,new LinearLayout.LayoutParams(-1,dp(420)));new AlertDialog.Builder(this).setTitle("Inspect / edit generated file").setMessage("Edits remain local project overrides and are included in the next explicit GitHub build. AIDao will not execute this text on-device.").setView(box).setPositiveButton("Save Override",(d,w)->{prefs.edit().putString("override::"+path,src.getText().toString()).putString("stage","SOURCE MODIFIED").remove("ci_state").remove("run_url").apply();setLast(TaskExecutionState.VERIFYING);workspace();}).setNeutralButton("Reset File",(d,w)->{prefs.edit().remove("override::"+path).apply();workspace();}).setNegativeButton("Close",null).show();}
    private boolean hasOverride(String path){return prefs.contains("override::"+path);}
    private void confirmClearOverrides(){new AlertDialog.Builder(this).setTitle("Clear manual edits?").setMessage("Generated source will return to AIDao's deterministic output. Your brief, plan, and directed knowledge are preserved.").setPositiveButton("Clear",(d,w)->{SharedPreferences.Editor e=prefs.edit();for(String k:new HashSet<>(prefs.getAll().keySet()))if(k.startsWith("override::"))e.remove(k);e.apply();workspace();}).setNegativeButton("Cancel",null).show();}

    private void builds(){heading("Build pipeline");boolean planned=prefs.contains("tasks"),gen=prefs.getBoolean("generated",false);String ci=prefs.getString("ci_state","Not sent");card("1 · Project context","Complete",GREEN);card("2 · Structured plan",planned?"Ready":"Waiting",planned?GREEN:MUTED);card("3 · Source generation",gen?"Generated & locally verified":"Waiting",gen?GREEN:YELLOW);card("4 · GitHub Android CI",ci,colorForState(ci));String artifact=prefs.getString("artifact_name","");if(!artifact.isEmpty())card("APK artifact",artifact+" · verified by trusted CI",GREEN);if(!planned)return;if(!gen){Button g=primary("Generate Real Android Source");g.setOnClickListener(v->generateSource());content.addView(g,lp(-1,dp(50),0,dp(12),0,0));}else{Button gh=primary("Configure GitHub & Build");gh.setOnClickListener(v->{tab=5;workspace();});content.addView(gh,lp(-1,dp(50),0,dp(12),0,0));}String url=prefs.getString("run_url",null);if(url!=null){Button open=secondary("Open CI Run / APK Artifact");open.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url))));content.addView(open,lp(-1,dp(50),0,dp(10),0,0));}String repair=prefs.getString("repair","");if(!repair.isEmpty())card("Last bounded repair",repair,YELLOW);}
    private void generateSource(){List<String> ts=decode(prefs.getString("tasks",""));setAll(ts,TaskExecutionState.IN_PROGRESS);GeneratedProject g=regenerateWithOverrides();boolean ok=true;for(String n:g.verificationNotes)if(n.startsWith("FAIL"))ok=false;if(ok){setAll(ts,TaskExecutionState.VERIFYING);SharedPreferences.Editor e=prefs.edit().putBoolean("generated",true).putString("stage","SOURCE READY");for(int i=0;i<Math.min(ts.size(),Math.max(1,ts.size()-1));i++)e.putString("task_"+i,TaskExecutionState.COMPLETE.name());if(!ts.isEmpty())e.putString("task_"+(ts.size()-1),TaskExecutionState.VERIFYING.name());e.apply();}else{prefs.edit().putString("stage","SOURCE BLOCKED").apply();setAll(ts,TaskExecutionState.BLOCKED);}workspace();}

    private void knowledge(){heading("Directed knowledge");card("Safe ingestion boundary","Import explicitly shared text, JSON, XML, Markdown, or source/reference material as planning knowledge. AIDao does not silently execute imported content, APKs, scripts, installers, or commands.",GREEN);String names=prefs.getString("knowledge_names","");String text=prefs.getString("knowledge_text","");if(names.isEmpty())card("No knowledge added","Your brief and refinement context are currently the only planning inputs.",MUTED);else{card("Imported material",names,GREEN);card("Planning excerpt",bounded(text,1400),BLUE);}Button add=primary("Add User-Shared File");add.setOnClickListener(v->pickKnowledge());content.addView(add,lp(-1,dp(50),0,dp(12),0,dp(8)));if(!names.isEmpty()){Button replan=secondary("Regenerate Plan With Knowledge");replan.setOnClickListener(v->{prefs.edit().remove("requirements").remove("tasks").remove("assumptions").putBoolean("generated",false).putString("stage","KNOWLEDGE READY").apply();generatePlan();});content.addView(replan,lp(-1,dp(50),0,dp(8),0,dp(8)));Button clear=secondary("Clear Directed Knowledge");clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Clear directed knowledge?").setMessage("This removes imported planning excerpts but does not change the original file on your device.").setPositiveButton("Clear",(d,w)->{prefs.edit().remove("knowledge_names").remove("knowledge_text").apply();workspace();}).setNegativeButton("Cancel",null).show());content.addView(clear,lp(-1,dp(48),0,dp(6),0,0));}}
    private void pickKnowledge(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"text/plain","text/markdown","text/xml","application/xml","application/json","text/x-java-source","text/x-kotlin"});startActivityForResult(i,PICK_KNOWLEDGE);}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=PICK_KNOWLEDGE||resultCode!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();try{String name=displayName(uri);String mime=getContentResolver().getType(uri);String raw=readBounded(uri,200000);KnowledgeDocument doc=KnowledgeDocument.fromUserSharedText(name,mime,"Android document picker",raw);if(!doc.mayUseAsPlanningKnowledge()){new AlertDialog.Builder(this).setTitle("File not used").setMessage("This file looks executable/binary or does not contain usable text. AIDao will not execute imported material.").setPositiveButton("OK",null).show();return;}String names=prefs.getString("knowledge_names","");String prior=prefs.getString("knowledge_text","");prefs.edit().putString("knowledge_names",names.isEmpty()?doc.displayName:names+", "+doc.displayName).putString("knowledge_text",bounded(prior+"\n["+doc.displayName+"]\n"+doc.boundedPlanningExcerpt(),24000)).putString("stage","KNOWLEDGE READY").apply();tab=4;workspace();}catch(Exception e){new AlertDialog.Builder(this).setTitle("Import failed").setMessage(safe(e.getMessage())).setPositiveButton("OK",null).show();}}
    private String displayName(Uri uri){String out="Shared material";Cursor c=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null);if(c!=null){try{if(c.moveToFirst())out=c.getString(0);}finally{c.close();}}return out==null?"Shared material":out;}
    private String readBounded(Uri uri,int max)throws Exception{InputStream in=getContentResolver().openInputStream(uri);if(in==null)throw new IOException("Unable to open selected file");ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[4096];int total=0,n;while((n=in.read(buf))!=-1&&total<max){int take=Math.min(n,max-total);out.write(buf,0,take);total+=take;}in.close();return new String(out.toByteArray(),StandardCharsets.UTF_8);}

    private void github(){heading("GitHub build connection");if(!prefs.getBoolean("generated",false)){card("Generated source required","Generate and verify the local Android source tree before sending anything to GitHub.",YELLOW);return;}card("Permission model",GitHubGeneratedBuildClient.TOKEN_PERMISSION_SUMMARY+". Workflows write is not required. The token is kept only for this build session and is never stored.",BLUE);EditText repo=input("owner/repository",prefs.getString("repo","IcyKokane/AIDaoPublic"));EditText token=input("Fine-grained GitHub token (not saved)","");token.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);content.addView(repo);content.addView(token,lp(-1,-2,0,dp(8),0,0));content.addView(text("This explicit action uploads generated source to an isolated generated-project branch and triggers the trusted generated-project workflow already on the repository default branch. AIDao never modifies the default branch with generated app source.",12,MUTED,false),lp(-1,-2,0,dp(8),0,dp(10)));if(building)card("Build running",prefs.getString("ci_state","Working…"),PURPLE);Button send=primary(building?"Build in progress…":"Send Generated Source & Build");send.setEnabled(!building);send.setOnClickListener(v->{String r=repo.getText().toString().trim(),t=token.getText().toString();if(r.isEmpty()||t.isEmpty()){Toast.makeText(this,"Repository and session token are required",Toast.LENGTH_SHORT).show();return;}prefs.edit().putString("repo",r).apply();sessionToken=t;startRemoteBuild(r,t);});content.addView(send,lp(-1,dp(52),0,dp(12),0,0));String run=prefs.getString("run_url",null);if(run!=null){Button open=secondary("Open Latest CI Run / Artifact");open.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(run))));content.addView(open,lp(-1,dp(50),0,dp(10),0,0));}}
    private void startRemoteBuild(String repo,String token){building=true;updateCi("Preparing generated branch");prefs.edit().putString("stage","BUILD RUNNING").apply();new Thread(()->{try{GitHubGeneratedBuildClient client=new GitHubGeneratedBuildClient();GeneratedProject g=regenerateWithOverrides();GitHubGeneratedBuildClient.BuildReceipt r=client.sendBuildAndWait(repo,token,g,(stage,detail)->{prefs.edit().putString("ci_state",stage+" · "+detail).apply();runOnUiThread(()->{if(tab==5)workspace();});});if(!r.success()){prefs.edit().putString("ci_state","CI failed · bounded repair starting").putString("run_url",r.runUrl).putString("repair",GitHubGeneratedBuildClient.boundedRepairHint(r.failureSummary)).apply();GeneratedProjectRepairer.RepairResult fix=new GeneratedProjectRepairer().repair(g,r.failureSummary);prefs.edit().putString("repair",fix.action).apply();GitHubGeneratedBuildClient.BuildReceipt retry=client.sendBuildAndWait(repo,token,fix.project,(s,d)->prefs.edit().putString("ci_state","Repair rebuild · "+s+" · "+d).apply());finishReceipt(retry);}else finishReceipt(r);}catch(Exception ex){prefs.edit().putString("ci_state","Blocked · "+safe(ex.getMessage())).putString("stage","BUILD BLOCKED").apply();setLast(TaskExecutionState.BLOCKED);}finally{sessionToken="";building=false;runOnUiThread(()->workspace());}}).start();}
    private void finishReceipt(GitHubGeneratedBuildClient.BuildReceipt r){if(r.success()){prefs.edit().putString("ci_state","Successful · APK artifact: "+r.artifactName).putString("artifact_name",r.artifactName).putString("run_url",r.runUrl).putString("stage","APK READY").putString("branch",r.branch).remove("repair").apply();setAll(decode(prefs.getString("tasks","")),TaskExecutionState.COMPLETE);}else{prefs.edit().putString("ci_state","Blocked after bounded repair · "+safe(r.failureSummary)).putString("run_url",r.runUrl).putString("stage","BUILD BLOCKED").apply();setLast(TaskExecutionState.BLOCKED);}}

    private GeneratedProject regenerateWithOverrides(){GeneratedProject base=new LocalSourceGenerator().generate(project,prefs.getString("brief",""),decode(prefs.getString("requirements","")),decode(prefs.getString("tasks","")));List<GeneratedProject.FileEntry> files=new ArrayList<>();for(GeneratedProject.FileEntry f:base.files){String override=prefs.getString("override::"+f.path,null);files.add(new GeneratedProject.FileEntry(f.path,override==null?f.content:override,f.taskHint));}return new GeneratedProject(base.projectName,base.packageName,files,verifyOverrides(base,files));}
    private List<String> verifyOverrides(GeneratedProject base,List<GeneratedProject.FileEntry> files){List<String> notes=new ArrayList<>(base.verificationNotes);int edited=0;for(GeneratedProject.FileEntry f:files)if(hasOverride(f.path))edited++;if(edited>0)notes.add("PASS "+edited+" user-controlled source override(s) included; CI remains authoritative verification");return notes;}
    private TaskExecutionState task(int i){return TaskExecutionState.fromStored(prefs.getString("task_"+i,TaskExecutionState.PLANNED.name()));}
    private void setAll(List<String> t,TaskExecutionState s){SharedPreferences.Editor e=prefs.edit();for(int i=0;i<t.size();i++)e.putString("task_"+i,s.name());e.apply();}
    private void setLast(TaskExecutionState s){List<String> t=decode(prefs.getString("tasks",""));if(!t.isEmpty())prefs.edit().putString("task_"+(t.size()-1),s.name()).apply();}
    private void updateCi(String s){prefs.edit().putString("ci_state",s).apply();}

    private LinearLayout nav(){LinearLayout n=row();n.setBackgroundColor(Color.rgb(13,14,18));String[] a={"Projects","AIDao","Activity","Settings"};for(int i=0;i<a.length;i++){final int x=i;TextView v=text(a[i],11,i==1?Color.WHITE:MUTED,i==1);v.setGravity(Gravity.CENTER);v.setMinHeight(dp(58));v.setOnClickListener(q->{if(x==0)showProjects();else if(x==1){project=prefs.getString("project_name",null);if(project==null)showProjects();else workspace();}else if(x==2)showActivity();else showSettings();});n.addView(v,new LinearLayout.LayoutParams(0,-2,1));}return n;}
    private void showActivity(){shell("Activity","Project execution status");String name=prefs.getString("project_name","No active project");card("Project",name+" · "+stateLabel(),BLUE);card("Build",prefs.getString("ci_state","No GitHub build started"),colorForState(prefs.getString("ci_state","")));String artifact=prefs.getString("artifact_name","");if(!artifact.isEmpty())card("Latest verified artifact",artifact,GREEN);}
    private void showSettings(){shell("Settings","AIDao controls");card("Planning provider","AIDao Local Planner · safe local/default path. External model configuration is not required for deterministic planning/source generation.",GREEN);card("Credential boundary","GitHub tokens are session-only and never persisted by AIDao.",GREEN);Button updates=primary("Check for Updates");updates.setOnClickListener(v->checkForUpdates());content.addView(updates,lp(-1,dp(50),0,dp(12),0,0));}
    private void checkForUpdates(){Toast.makeText(this,"Checking AIDao update metadata…",Toast.LENGTH_SHORT).show();new Thread(()->{try{URL u=new URL("https://raw.githubusercontent.com/IcyKokane/AIDaoPublic/main/updates/latest.json");HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestProperty("User-Agent","AIDao-Android");BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String line;while((line=r.readLine())!=null)b.append(line);r.close();c.disconnect();Matcher m=Pattern.compile("\\\"versionCode\\\"\\s*:\\s*(\\d+)").matcher(b.toString());Matcher n=Pattern.compile("\\\"version\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"").matcher(b.toString());int remote=m.find()?Integer.parseInt(m.group(1)):0;String version=n.find()?n.group(1):"unknown";runOnUiThread(()->new AlertDialog.Builder(this).setTitle(remote>BuildConfig.VERSION_CODE?"Update available":"AIDao is current").setMessage(remote>BuildConfig.VERSION_CODE?"Version "+version+" is available. Open the trusted AIDaoPublic GitHub Actions page to choose the artifact explicitly.":"Installed: "+BuildConfig.VERSION_NAME+"\nLatest metadata: "+version).setPositiveButton(remote>BuildConfig.VERSION_CODE?"Open GitHub":"OK",(d,w)->{if(remote>BuildConfig.VERSION_CODE)startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://github.com/IcyKokane/AIDaoPublic/actions/workflows/android.yml")));}).setNegativeButton(remote>BuildConfig.VERSION_CODE?"Later":null,null).show());}catch(Exception e){runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Update check failed").setMessage(safe(e.getMessage())).setPositiveButton("OK",null).show());}}).start();}

    private void heading(String s){content.addView(text(s,21,Color.WHITE,true),lp(-1,-2,0,0,0,dp(10)));}private void label(String s,int c){content.addView(text(s,11,c,true),lp(-1,-2,0,dp(16),0,dp(6)));}
    private View card(String title,String detail,int color){LinearLayout p=col();p.setPadding(dp(16),dp(15),dp(16),dp(15));p.setBackground(round(PANEL,14));LinearLayout r=row();TextView dot=text("◆",14,color,true);dot.setContentDescription("");r.addView(dot,lp(dp(34),-2,0,0,dp(8),0));LinearLayout l=col();l.addView(text(title,14,Color.WHITE,true));l.addView(text(detail,12,MUTED,false));r.addView(l,new LinearLayout.LayoutParams(0,-2,1));p.addView(r);content.addView(p,lp(-1,-2,0,0,0,dp(8)));return p;}
    private EditText input(String hint,String value){EditText e=new EditText(this);e.setTypeface(UI);e.setText(value);e.setHint(hint);e.setTextColor(Color.WHITE);e.setHintTextColor(MUTED);e.setTextSize(14);e.setSingleLine(true);e.setPadding(dp(16),0,dp(16),0);e.setBackground(round(PANEL,12));e.setMinHeight(dp(52));return e;}
    private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setTypeface(BOLD);b.setBackground(round(Color.rgb(82,89,245),14));b.setMinHeight(dp(48));return b;}private Button secondary(String s){Button b=primary(s);b.setBackground(round(PANEL,14));return b;}
    private TextView text(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setTypeface(bold?BOLD:UI);t.setLineSpacing(0,1.08f);return t;}
    private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}
    private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private GradientDrawable gradient(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(73,139,255),Color.rgb(139,79,255)});g.setCornerRadius(dp(14));return g;}
    private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private String stateLabel(){return prefs.getString("stage",prefs.getString("project_name",null)==null?"READY":"BRIEF READY");}
    private int color(TaskExecutionState s){if(s==TaskExecutionState.COMPLETE)return GREEN;if(s==TaskExecutionState.BLOCKED)return RED;if(s==TaskExecutionState.IN_PROGRESS||s==TaskExecutionState.VERIFYING)return PURPLE;return MUTED;}
    private int colorForState(String s){String v=s==null?"":s.toLowerCase(Locale.US);if(v.contains("successful")||v.contains("ready")||v.contains("verified"))return GREEN;if(v.contains("blocked")||v.contains("fail")||v.contains("error")||v.contains("403")||v.contains("401"))return RED;if(v.contains("recovery")||v.contains("waiting")||v.contains("not sent"))return YELLOW;return PURPLE;}
    private String titleFrom(String s){String v=s==null?"New Android App":s.trim().replaceAll("\\s+"," ");String[] words=v.split(" ");StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(words.length,7);i++){if(i>0)b.append(' ');String w=words[i];b.append(w.length()>0?Character.toUpperCase(w.charAt(0))+w.substring(1):w);}return b.length()==0?"New Android App":b.toString();}
    private String safe(String s){return s==null?"Unknown error":bounded(s,1400);}private String bounded(String s,int n){if(s==null)return "";return s.substring(0,Math.min(s.length(),n));}
    private String encode(List<String> a){return android.text.TextUtils.join("\u001f",a);}private List<String> decode(String s){if(s==null||s.isEmpty())return new ArrayList<>();return new ArrayList<>(Arrays.asList(s.split("\u001f",-1)));}
}
