package dev.thefoolish.aidao;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Rect;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.Window;
import android.view.WindowInsets;
import android.view.WindowManager;
import android.view.inputmethod.InputMethodManager;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class AIDaoActivityV3 extends Activity {
    private static final int BG=Color.rgb(18,19,24),HEADER=Color.rgb(22,23,29),PANEL=Color.rgb(29,31,39),PANEL_ALT=Color.rgb(35,38,48);
    private static final int MUTED=Color.rgb(157,162,178),BLUE=Color.rgb(80,148,255),PURPLE=Color.rgb(145,93,255),GREEN=Color.rgb(76,201,144),YELLOW=Color.rgb(235,190,80);
    private static final Typeface UI=Typeface.create("sans-serif",Typeface.NORMAL), UI_MEDIUM=Typeface.create("sans-serif-medium",Typeface.NORMAL), BRAND=Typeface.create("cursive",Typeface.BOLD);
    private static final String UPDATE_SOURCE="https://raw.githubusercontent.com/IcyKokane/AIDaoPublic/main/updates/latest.json";
    private static final String FALLBACK_DOWNLOAD_PAGE="https://github.com/IcyKokane/AIDaoPublic/actions/workflows/android.yml";
    private static final String REPO_PAGE="https://github.com/IcyKokane/AIDaoPublic";

    private LinearLayout root,header,content,bottomNav;
    private SharedPreferences prefs;
    private ProviderRegistry providers;
    private String currentProject="Starter Workspace",currentProjectState="APK READY";
    private int activeNav,workspaceTab,horizontalPad;
    private boolean updateCheckInProgress;

    @Override public void onCreate(Bundle state){
        super.onCreate(state);
        prefs=getSharedPreferences("aidao_workspace",MODE_PRIVATE);
        providers=new ProviderRegistry();
        Window w=getWindow();w.setStatusBarColor(BG);w.setNavigationBarColor(Color.rgb(12,13,17));w.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
        if(Build.VERSION.SDK_INT>=30)w.setDecorFitsSystemWindows(false);else w.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION);
        if(Build.VERSION.SDK_INT>=29)w.setNavigationBarContrastEnforced(false);
        showProjects();
    }

    private void buildShell(String title,String subtitle,boolean branded){
        horizontalPad=getResources().getConfiguration().smallestScreenWidthDp>=600?dp(30):dp(18);
        root=column();root.setBackgroundColor(BG);
        header=row();header.setGravity(Gravity.CENTER_VERTICAL);header.setBackgroundColor(HEADER);header.setPadding(horizontalPad,dp(28),horizontalPad,dp(14));
        TextView logo=brandText("A",21,Color.WHITE);logo.setGravity(Gravity.CENTER);GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{BLUE,PURPLE});g.setCornerRadius(dp(13));logo.setBackground(g);header.addView(logo,margins(dp(44),dp(44),0,0,dp(12),0));
        LinearLayout titles=column();titles.addView(branded?brandText(title,20,Color.WHITE):uiText(title,20,Color.WHITE,true));titles.addView(uiText(subtitle,12,MUTED,false),margins(-1,-2,0,dp(3),0,0));header.addView(titles,new LinearLayout.LayoutParams(0,-2,1));
        TextView ready=uiText("●",16,GREEN,true);ready.setGravity(Gravity.CENTER);ready.setContentDescription("AIDao ready");header.addView(ready,new LinearLayout.LayoutParams(dp(44),dp(44)));root.addView(header);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);content=column();content.setPadding(horizontalPad,dp(18),horizontalPad,dp(28));scroll.addView(content,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        bottomNav=createBottomNav();root.addView(bottomNav);setContentView(root);installInsets();installLegacyImeDetector();
    }

    private void installInsets(){
        if(Build.VERSION.SDK_INT<23)return;
        root.setOnApplyWindowInsetsListener((v,insets)->{int top,bottom,left,right,imeBottom=0;boolean imeVisible=false;
            if(Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout()),ime=insets.getInsets(WindowInsets.Type.ime());top=bars.top;bottom=bars.bottom;left=bars.left;right=bars.right;imeBottom=ime.bottom;imeVisible=insets.isVisible(WindowInsets.Type.ime());}
            else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();left=insets.getSystemWindowInsetLeft();right=insets.getSystemWindowInsetRight();}
            int safeLeft=Math.max(horizontalPad,left+dp(12)),safeRight=Math.max(horizontalPad,right+dp(12));header.setPadding(safeLeft,top+dp(28),safeRight,dp(14));bottomNav.setPadding(Math.max(dp(8),left+dp(6)),dp(7),Math.max(dp(8),right+dp(6)),Math.max(bottom,dp(6))+dp(8));
            if(Build.VERSION.SDK_INT>=30){int keyboard=imeVisible?Math.max(0,imeBottom-bottom):0;bottomNav.setVisibility(imeVisible?View.GONE:View.VISIBLE);content.setPadding(safeLeft,dp(18),safeRight,dp(28)+keyboard+(imeVisible?dp(12):0));}else content.setPadding(safeLeft,dp(18),safeRight,dp(28));return insets;});root.requestApplyInsets();
    }
    private void installLegacyImeDetector(){if(Build.VERSION.SDK_INT>=30)return;root.getViewTreeObserver().addOnGlobalLayoutListener(()->{Rect r=new Rect();root.getWindowVisibleDisplayFrame(r);int hidden=root.getRootView().getHeight()-r.bottom;bottomNav.setVisibility(hidden>root.getRootView().getHeight()*.18f?View.GONE:View.VISIBLE);});}

    private void showProjects(){
        activeNav=0;buildShell("AIDao","Developer workspace",true);
        LinearLayout hero=panel(PANEL);hero.addView(uiText("BUILD WITH AIDAO",11,BLUE,true));hero.addView(brandText("What do you want to create?",25,Color.WHITE),margins(-1,-2,0,dp(6),0,dp(8)));hero.addView(uiText("Describe an Android product. AIDao turns the brief into editable requirements, implementation tasks, project context, and a visible build workflow.",14,MUTED,false));Button create=primary("New Project");create.setOnClickListener(v->openNewProjectDialog());hero.addView(create,margins(-1,dp(50),0,dp(16),0,0));content.addView(hero);
        content.addView(brandText("Recent projects",18,Color.WHITE),margins(-1,-2,0,dp(22),0,dp(8)));String savedName=prefs.getString("project_name",null),savedBrief=prefs.getString("project_brief",null);if(savedName!=null&&savedBrief!=null)content.addView(projectCard(savedName,planExists(savedName)?"PLAN READY":"PLANNING",planExists(savedName)?GREEN:BLUE,savedBrief));content.addView(projectCard("Anime Library","PLANNING",BLUE,"Provider plugin architecture · Repository support"),margins(-1,-2,0,savedName==null?0:dp(10),0,0));content.addView(projectCard("Starter Workspace","APK READY",GREEN,"Baseline AIDao build pipeline"),margins(-1,-2,0,dp(10),0,0));
        content.addView(brandText("Activity",18,Color.WHITE),margins(-1,-2,0,dp(24),0,dp(8)));content.addView(activity("◆",GREEN,"Planning engine ready","Local provider can generate editable project plans"));content.addView(activity("↗",BLUE,"GitHub connected","IcyKokane / AIDaoPublic"),margins(-1,-2,0,dp(8),0,0));View update=activity("↓",PURPLE,"Check for Updates","Installed: "+BuildConfig.VERSION_NAME+" · Tap to check");update.setOnClickListener(v->checkForUpdates());update.setClickable(true);content.addView(update,margins(-1,-2,0,dp(8),0,0));
    }

    private View projectCard(String name,String state,int color,String detail){LinearLayout card=panel(PANEL);card.setClickable(true);card.setFocusable(true);card.setOnClickListener(v->showWorkspace(name,state));LinearLayout top=row();TextView icon=uiText("◇",20,BLUE,true);icon.setGravity(Gravity.CENTER);icon.setBackground(round(PANEL_ALT,11));top.addView(icon,margins(dp(44),dp(44),0,0,dp(12),0));LinearLayout names=column();names.addView(uiText(name,17,Color.WHITE,true));names.addView(uiText("Android",12,MUTED,false));top.addView(names,new LinearLayout.LayoutParams(0,-2,1));TextView badge=uiText(state,10,color,true);badge.setGravity(Gravity.CENTER);badge.setPadding(dp(9),dp(5),dp(9),dp(5));badge.setBackground(stroke(PANEL_ALT,color,10));top.addView(badge);card.addView(top);card.addView(uiText(detail,13,Color.rgb(205,208,218),false),margins(-1,-2,0,dp(12),0,0));return card;}

    private void showWorkspace(String name,String state){currentProject=name;currentProjectState=state;workspaceTab=0;activeNav=1;rebuildWorkspace();}
    private void rebuildWorkspace(){buildShell(currentProject,"Project workspace · "+currentProjectState,false);addWorkspaceTabs();renderWorkspaceTab();}
    private void addWorkspaceTabs(){HorizontalScrollView s=new HorizontalScrollView(this);s.setHorizontalScrollBarEnabled(false);LinearLayout tabs=row();String[] names={"Chat","Plan","Tasks","Files","Builds","GitHub"};for(int i=0;i<names.length;i++){final int index=i;boolean selected=workspaceTab==i;TextView t=uiText(names[i],12,selected?Color.WHITE:MUTED,selected);t.setGravity(Gravity.CENTER);t.setPadding(dp(14),dp(10),dp(14),dp(10));t.setMinHeight(dp(44));t.setBackground(round(selected?Color.rgb(71,78,104):PANEL,12));t.setOnClickListener(v->{workspaceTab=index;rebuildWorkspace();});tabs.addView(t,margins(-2,-2,0,0,dp(7),0));}s.addView(tabs);content.addView(s,new LinearLayout.LayoutParams(-1,-2));}
    private void renderWorkspaceTab(){if(workspaceTab==0)renderChat();else if(workspaceTab==1)renderPlan();else if(workspaceTab==2)renderTasks();else if(workspaceTab==3)renderFiles();else if(workspaceTab==4)renderBuilds();else renderGitHub();}

    private String key(String suffix){return "v3_"+Integer.toHexString(currentProject.toLowerCase().hashCode())+"_"+suffix;}
    private boolean planExists(String project){String old=currentProject;currentProject=project;boolean found=prefs.contains(key("requirements"));currentProject=old;return found;}
    private String projectBrief(){return currentProject.equals(prefs.getString("project_name",""))?prefs.getString("project_brief",""):currentProject.equals("Anime Library")?"Build an Android anime library with repository-based replaceable provider plugins and media browsing.":"Maintain the AIDao Android developer workspace and verified APK build pipeline.";}
    private String context(){return prefs.getString(key("chat"),"");}

    private void renderChat(){content.addView(uiText("# ai-build",13,MUTED,true),margins(-1,-2,0,dp(18),0,dp(10)));content.addView(message("AIDao","Project context stays local until you deliberately configure a remote model provider. Use Plan when you want AIDao to convert this context into requirements and tasks."));String h=context();if(!h.isEmpty())for(String e:h.split("\\n---\\n"))if(!e.trim().isEmpty())content.addView(message("You",e.trim()),margins(-1,-2,0,dp(10),0,0));LinearLayout composer=panel(PANEL);EditText prompt=new EditText(this);prompt.setHint("Add requirements, corrections, or build direction…");prompt.setHintTextColor(MUTED);prompt.setTextColor(Color.WHITE);prompt.setTextSize(14);prompt.setTypeface(UI);prompt.setMinLines(2);prompt.setMaxLines(5);prompt.setBackgroundColor(Color.TRANSPARENT);composer.addView(prompt);Button send=primary("Add to Project Context");send.setOnClickListener(v->{String msg=prompt.getText().toString().trim();if(msg.isEmpty())return;String old=context();prefs.edit().putString(key("chat"),old.isEmpty()?msg:old+"\n---\n"+msg).apply();hideKeyboard(prompt);rebuildWorkspace();});composer.addView(send,margins(-1,dp(48),0,dp(8),0,0));content.addView(composer,margins(-1,-2,0,dp(18),0,0));}

    private void renderPlan(){content.addView(brandText("Project plan",20,Color.WHITE),margins(-1,-2,0,dp(18),0,dp(8)));content.addView(activity("◆",BLUE,"Project brief",projectBrief()));if(!prefs.contains(key("requirements"))){LinearLayout callout=panel(PANEL_ALT);callout.addView(uiText("No generated plan yet",16,Color.WHITE,true));callout.addView(uiText("AIDao can analyze the saved brief and project conversation with the selected provider. The offline planner is currently the default and performs no network call.",13,MUTED,false),margins(-1,-2,0,dp(6),0,0));Button generate=primary("Generate Project Plan");generate.setOnClickListener(v->generatePlan());callout.addView(generate,margins(-1,dp(48),0,dp(12),0,0));content.addView(callout,margins(-1,-2,0,dp(10),0,0));return;}
        content.addView(uiText("REQUIREMENTS",11,BLUE,true),margins(-1,-2,0,dp(18),0,dp(8)));List<String> req=decode(prefs.getString(key("requirements"),""));for(int i=0;i<req.size();i++){final int index=i;View r=editableRow("R"+(i+1),req.get(i),()->editListItem("Requirement",key("requirements"),index));content.addView(r,margins(-1,-2,0,i==0?0:dp(8),0,0));}
        content.addView(uiText("ASSUMPTIONS & SAFETY",11,YELLOW,true),margins(-1,-2,0,dp(20),0,dp(8)));for(String a:decode(prefs.getString(key("assumptions"),"")))content.addView(activity("!",YELLOW,"Assumption",a),margins(-1,-2,0,dp(8),0,0));Button regenerate=secondary("Regenerate from Current Context");regenerate.setOnClickListener(v->confirmRegenerate());content.addView(regenerate,margins(-1,dp(48),0,dp(16),0,0));}

    private void renderTasks(){content.addView(brandText("Implementation tasks",20,Color.WHITE),margins(-1,-2,0,dp(18),0,dp(8)));if(!prefs.contains(key("tasks"))){content.addView(activity("○",MUTED,"No tasks generated","Generate the project plan first."));return;}List<String> tasks=decode(prefs.getString(key("tasks"),""));int done=0;for(int i=0;i<tasks.size();i++)if(prefs.getBoolean(key("task_done_"+i),false))done++;content.addView(activity("✓",done==tasks.size()?GREEN:BLUE,"Progress",done+" of "+tasks.size()+" tasks marked complete"));for(int i=0;i<tasks.size();i++){final int index=i;boolean isDone=prefs.getBoolean(key("task_done_"+i),false);LinearLayout row=panel(PANEL);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);TextView check=uiText(isDone?"✓":"○",20,isDone?GREEN:MUTED,true);check.setGravity(Gravity.CENTER);row.addView(check,margins(dp(40),dp(40),0,0,dp(9),0));TextView label=uiText(tasks.get(i),13,isDone?MUTED:Color.WHITE,false);row.addView(label,new LinearLayout.LayoutParams(0,-2,1));row.setClickable(true);row.setOnClickListener(v->{prefs.edit().putBoolean(key("task_done_"+index),!prefs.getBoolean(key("task_done_"+index),false)).apply();rebuildWorkspace();});content.addView(row,margins(-1,-2,0,dp(8),0,0));}Button export=secondary("Share Project Specification");export.setOnClickListener(v->shareSpec());content.addView(export,margins(-1,dp(48),0,dp(16),0,0));}

    private void generatePlan(){try{ModelProvider provider=providers.selected();ModelProvider.Result result=provider.plan(new ModelProvider.Request(currentProject,projectBrief(),context()));savePlan(result.plan);prefs.edit().putString(key("provider"),result.providerName).putString(key("summary"),result.summary).apply();currentProjectState="PLAN READY";Toast.makeText(this,"Plan generated with "+result.providerName,Toast.LENGTH_SHORT).show();rebuildWorkspace();}catch(Exception e){new AlertDialog.Builder(this).setTitle("Planning failed").setMessage("AIDao could not generate the plan. No project data was changed.").setPositiveButton("OK",null).show();}}
    private void savePlan(ProjectPlanner.Plan plan){prefs.edit().putString(key("requirements"),encode(plan.requirements)).putString(key("tasks"),encode(plan.tasks)).putString(key("assumptions"),encode(plan.assumptions)).apply();for(int i=0;i<50;i++)prefs.edit().remove(key("task_done_"+i)).apply();}
    private void confirmRegenerate(){new AlertDialog.Builder(this).setTitle("Regenerate project plan?").setMessage("Requirements and tasks will be rebuilt from the current brief and conversation. Task completion marks will reset.").setPositiveButton("Regenerate",(d,w)->generatePlan()).setNegativeButton("Cancel",null).show();}
    private void editListItem(String title,String prefKey,int index){List<String> items=decode(prefs.getString(prefKey,""));if(index<0||index>=items.size())return;EditText input=new EditText(this);input.setText(items.get(index));input.setTextColor(Color.BLACK);input.setMinLines(3);new AlertDialog.Builder(this).setTitle("Edit "+title).setView(input).setPositiveButton("Save",(d,w)->{String value=input.getText().toString().trim();if(!value.isEmpty()){items.set(index,value);prefs.edit().putString(prefKey,encode(items)).apply();rebuildWorkspace();}}).setNegativeButton("Cancel",null).show();}
    private View editableRow(String mark,String body,Runnable action){LinearLayout r=panel(PANEL);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);TextView icon=uiText(mark,12,BLUE,true);icon.setGravity(Gravity.CENTER);r.addView(icon,margins(dp(38),dp(38),0,0,dp(10),0));TextView label=uiText(body,13,Color.WHITE,false);r.addView(label,new LinearLayout.LayoutParams(0,-2,1));TextView edit=uiText("Edit",12,BLUE,true);edit.setPadding(dp(12),dp(10),dp(4),dp(10));r.addView(edit);r.setClickable(true);r.setOnClickListener(v->action.run());return r;}

    private void renderFiles(){content.addView(brandText("Project files",20,Color.WHITE),margins(-1,-2,0,dp(18),0,dp(8)));content.addView(activity("▤",BLUE,"app/","Android application module"));content.addView(activity("▤",BLUE,"README.md","Project brief and generated specification"),margins(-1,-2,0,dp(8),0,0));content.addView(activity("▤",BLUE,".github/workflows/","Automated build and verification"),margins(-1,-2,0,dp(8),0,0));}
    private void renderBuilds(){content.addView(brandText("Build pipeline",20,Color.WHITE),margins(-1,-2,0,dp(18),0,dp(8)));boolean planned=prefs.contains(key("tasks"));content.addView(buildEvent("Project context","Complete",GREEN));content.addView(buildEvent("Structured plan",planned?"Ready":"Waiting",planned?GREEN:PURPLE),margins(-1,-2,0,dp(8),0,0));content.addView(buildEvent("Source generation","Not connected",YELLOW),margins(-1,-2,0,dp(8),0,0));content.addView(buildEvent("Android CI",currentProject.equals("Starter Workspace")?"Successful":"Awaiting generated source",currentProject.equals("Starter Workspace")?GREEN:MUTED),margins(-1,-2,0,dp(8),0,0));content.addView(uiText("AIDao will not pretend a project APK exists until source generation is connected and CI reports success.",12,MUTED,false),margins(-1,-2,0,dp(12),0,0));}
    private void renderGitHub(){content.addView(brandText("GitHub",20,Color.WHITE),margins(-1,-2,0,dp(18),0,dp(8)));content.addView(activity("↗",BLUE,"AIDaoPublic","Authoritative AIDao source and Android CI repository"));Button open=primary("Open Repository");open.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(REPO_PAGE))));content.addView(open,margins(-1,dp(48),0,dp(12),0,0));}

    private void shareSpec(){StringBuilder s=new StringBuilder("AIDao Project Specification\n\nProject: ").append(currentProject).append("\nBrief: ").append(projectBrief()).append("\n\nRequirements\n");for(String r:decode(prefs.getString(key("requirements"),"")))s.append("- ").append(r).append('\n');s.append("\nImplementation Tasks\n");List<String> tasks=decode(prefs.getString(key("tasks"),""));for(int i=0;i<tasks.size();i++)s.append(prefs.getBoolean(key("task_done_"+i),false)?"[done] ":"[ ] ").append(tasks.get(i)).append('\n');Intent send=new Intent(Intent.ACTION_SEND);send.setType("text/plain");send.putExtra(Intent.EXTRA_TEXT,s.toString());startActivity(Intent.createChooser(send,"Share project specification"));}

    private void showAssistant(){activeNav=1;buildShell("AIDao","AI build console",true);content.addView(brandText("Planning provider",21,Color.WHITE));ModelProvider p=providers.selected();content.addView(activity("◆",GREEN,p.displayName(),p.isRemote()?"Remote provider":"Offline · no network model request"),margins(-1,-2,0,dp(12),0,0));content.addView(uiText("AIDao currently uses the safe local planning provider. Remote providers can be added later through the provider boundary without giving a model authority to install, publish, spend, or make destructive changes.",13,MUTED,false),margins(-1,-2,0,dp(10),0,dp(16)));Button open=primary("Open Saved Project");open.setOnClickListener(v->{String name=prefs.getString("project_name","Starter Workspace");showWorkspace(name,planExists(name)?"PLAN READY":"PLANNING");});content.addView(open,margins(-1,dp(48),0,dp(8),0,0));}
    private void showActivity(){activeNav=2;buildShell("Activity","Build and update status",false);content.addView(brandText("System activity",21,Color.WHITE));content.addView(activity("✓",GREEN,"Planning engine","Structured project planning available"),margins(-1,-2,0,dp(12),0,0));content.addView(activity("✓",GREEN,"Android CI pipeline","AIDao application builds are verified through GitHub Actions"),margins(-1,-2,0,dp(8),0,0));View update=activity("↓",PURPLE,"Check for Updates","Current install: "+BuildConfig.VERSION_NAME);update.setOnClickListener(v->checkForUpdates());update.setClickable(true);content.addView(update,margins(-1,-2,0,dp(8),0,0));}
    private void showSettings(){activeNav=3;buildShell("Settings","AIDao preferences and updates",false);LinearLayout version=panel(PANEL);version.addView(uiText("AIDao "+BuildConfig.VERSION_NAME,17,Color.WHITE,true));version.addView(uiText("Updates use the official AIDaoPublic metadata and always require you to open the verified build page yourself.",13,MUTED,false),margins(-1,-2,0,dp(8),0,0));Button check=primary("Check for Updates");check.setOnClickListener(v->checkForUpdates());version.addView(check,margins(-1,dp(50),0,dp(14),0,0));content.addView(version);ModelProvider p=providers.selected();content.addView(activity("◆",GREEN,"Model provider: "+p.displayName(),p.isRemote()?"Remote":"Local/offline planning"),margins(-1,-2,0,dp(12),0,0));Button clear=secondary("Clear Local Workspace Data");clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Clear local workspace data?").setMessage("Saved briefs, conversations, generated plans, and task progress will be removed from this device.").setPositiveButton("Clear",(d,w)->{prefs.edit().clear().apply();showProjects();}).setNegativeButton("Cancel",null).show());content.addView(clear,margins(-1,dp(48),0,dp(12),0,0));}

    private LinearLayout createBottomNav(){LinearLayout nav=row();nav.setGravity(Gravity.CENTER);nav.setBackgroundColor(Color.rgb(13,14,18));nav.setPadding(dp(8),dp(7),dp(8),dp(12));String[] names={"Projects","AIDao","Activity","Settings"},icons={"▦","◇","≋","⚙"};for(int i=0;i<names.length;i++){final int index=i;boolean selected=i==activeNav;LinearLayout item=column();item.setGravity(Gravity.CENTER);item.setMinimumHeight(dp(58));item.setClickable(true);item.setFocusable(true);item.setContentDescription(names[i]+(selected?", selected":""));item.addView(uiText(icons[i],17,selected?BLUE:MUTED,true));item.addView(uiText(names[i],10,selected?Color.WHITE:MUTED,selected));item.setOnClickListener(v->{if(index==0)showProjects();else if(index==1)showAssistant();else if(index==2)showActivity();else showSettings();});nav.addView(item,new LinearLayout.LayoutParams(0,-2,1));}return nav;}

    private void openNewProjectDialog(){EditText input=new EditText(this);input.setHint("Example: Build an anime library app with provider plugins…");input.setMinLines(5);input.setTextSize(14);input.setTypeface(UI);new AlertDialog.Builder(this).setTitle("Create a project").setMessage("Describe the Android app in ordinary language.").setView(input).setPositiveButton("Create Project",(d,w)->{String raw=input.getText().toString().trim();if(raw.isEmpty())return;String name=makeProjectName(raw);prefs.edit().putString("project_name",name).putString("project_brief",raw).apply();showWorkspace(name,"PLANNING");}).setNegativeButton("Cancel",null).show();}
    private String makeProjectName(String raw){String[] words=raw.replaceAll("\\s+"," ").trim().split(" ");StringBuilder n=new StringBuilder();for(int i=0;i<Math.min(words.length,4);i++){String w=words[i].replaceAll("[^A-Za-z0-9'-]","");if(w.isEmpty())continue;if(n.length()>0)n.append(' ');n.append(Character.toUpperCase(w.charAt(0))).append(w.substring(1));}return n.length()==0?"New Project":n.toString();}

    private void checkForUpdates(){if(updateCheckInProgress){Toast.makeText(this,"Update check already in progress",Toast.LENGTH_SHORT).show();return;}updateCheckInProgress=true;Toast.makeText(this,"Checking AIDaoPublic…",Toast.LENGTH_SHORT).show();new Thread(()->{HttpURLConnection c=null;try{c=(HttpURLConnection)new URL(UPDATE_SOURCE).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(8000);c.setUseCaches(false);c.setRequestProperty("Cache-Control","no-cache, no-store");c.setRequestProperty("User-Agent","AIDao-Android/"+BuildConfig.VERSION_NAME);if(c.getResponseCode()!=200)throw new IllegalStateException();BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder b=new StringBuilder();String line;while((line=r.readLine())!=null)b.append(line);r.close();String latest=jsonValue(b.toString(),"version"),download=jsonValue(b.toString(),"downloadUrl"),notes=jsonValue(b.toString(),"notes");if(latest==null)throw new IllegalStateException();runOnUiThread(()->{updateCheckInProgress=false;showUpdateResult(latest,download,notes);});}catch(Exception e){runOnUiThread(()->{updateCheckInProgress=false;new AlertDialog.Builder(this).setTitle("Unable to check for updates").setMessage("AIDao could not reach its official AIDaoPublic update source. Check your connection and try again.").setPositiveButton("OK",null).show();});}finally{if(c!=null)c.disconnect();}}).start();}
    private void showUpdateResult(String latest,String download,String notes){boolean newer=compareVersions(latest,BuildConfig.VERSION_NAME)>0;StringBuilder m=new StringBuilder("Installed: ").append(BuildConfig.VERSION_NAME).append("\nAvailable: ").append(latest);if(notes!=null&&!notes.trim().isEmpty())m.append("\n\nWhat changed\n").append(notes.trim());AlertDialog.Builder d=new AlertDialog.Builder(this).setTitle(newer?"Update available":"AIDao is current").setMessage(m.toString());if(newer)d.setPositiveButton("Open verified build page",(x,w)->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(verifiedDownloadTarget(download))))).setNegativeButton("Not now",null);else d.setPositiveButton("Done",null);d.show();}
    private String verifiedDownloadTarget(String value){if(value==null)return FALLBACK_DOWNLOAD_PAGE;try{Uri u=Uri.parse(value.trim());String p=u.getPath();return "https".equalsIgnoreCase(u.getScheme())&&"github.com".equalsIgnoreCase(u.getHost())&&p!=null&&(p.equals("/IcyKokane/AIDaoPublic")||p.startsWith("/IcyKokane/AIDaoPublic/"))?u.toString():FALLBACK_DOWNLOAD_PAGE;}catch(Exception e){return FALLBACK_DOWNLOAD_PAGE;}}
    private String jsonValue(String json,String key){Matcher m=Pattern.compile("\\\""+Pattern.quote(key)+"\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"").matcher(json);return m.find()?m.group(1).replace("\\/","/").replace("\\n","\n"):null;}
    private int compareVersions(String a,String b){try{String[] aa=a.replaceAll("[^0-9.]","").split("\\."),bb=b.replaceAll("[^0-9.]","").split("\\.");for(int i=0;i<Math.max(aa.length,bb.length);i++){int av=i<aa.length&&!aa[i].isEmpty()?Integer.parseInt(aa[i]):0,bv=i<bb.length&&!bb[i].isEmpty()?Integer.parseInt(bb[i]):0;if(av!=bv)return Integer.compare(av,bv);}return 0;}catch(Exception e){return 0;}}

    private String encode(List<String> values){StringBuilder b=new StringBuilder();for(String v:values){if(b.length()>0)b.append("\n---ITEM---\n");b.append(v.replace("\n"," "));}return b.toString();}
    private List<String> decode(String raw){List<String> out=new ArrayList<>();if(raw==null||raw.trim().isEmpty())return out;for(String v:raw.split("\\n---ITEM---\\n"))if(!v.trim().isEmpty())out.add(v.trim());return out;}
    private View message(String author,String body){LinearLayout r=row();r.setGravity(Gravity.TOP);TextView avatar=brandText(author.equals("You")?"Y":"A",17,Color.WHITE);avatar.setGravity(Gravity.CENTER);avatar.setBackground(round(author.equals("You")?PURPLE:BLUE,12));r.addView(avatar,margins(dp(42),dp(42),0,0,dp(11),0));LinearLayout bubble=panel(PANEL);bubble.addView(uiText(author,12,Color.rgb(208,212,226),true));bubble.addView(uiText(body,14,Color.WHITE,false),margins(-1,-2,0,dp(6),0,0));r.addView(bubble,new LinearLayout.LayoutParams(0,-2,1));return r;}
    private View buildEvent(String title,String state,int color){LinearLayout r=panel(PANEL_ALT);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);TextView dot=uiText("●",11,color,true);r.addView(dot,margins(dp(28),dp(28),0,0,dp(7),0));LinearLayout info=column();info.addView(uiText(title,13,Color.WHITE,true));info.addView(uiText(state,11,MUTED,false));r.addView(info,new LinearLayout.LayoutParams(0,-2,1));return r;}
    private View activity(String mark,int color,String title,String detail){LinearLayout r=panel(PANEL);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);r.setMinimumHeight(dp(58));TextView icon=uiText(mark,15,color,true);icon.setGravity(Gravity.CENTER);r.addView(icon,margins(dp(36),dp(36),0,0,dp(10),0));LinearLayout labels=column();labels.addView(uiText(title,14,Color.WHITE,true));labels.addView(uiText(detail,11,MUTED,false));r.addView(labels,new LinearLayout.LayoutParams(0,-2,1));return r;}
    private void hideKeyboard(View v){try{InputMethodManager imm=(InputMethodManager)getSystemService(INPUT_METHOD_SERVICE);if(imm!=null)imm.hideSoftInputFromWindow(v.getWindowToken(),0);v.clearFocus();}catch(Exception ignored){}}
    private Button primary(String value){Button b=new Button(this);b.setText(value);b.setTextSize(14);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setTypeface(UI_MEDIUM);b.setMinHeight(dp(48));b.setBackground(round(Color.rgb(83,91,242),12));return b;}
    private Button secondary(String value){Button b=primary(value);b.setBackground(stroke(PANEL,Color.rgb(73,78,94),12));return b;}
    private TextView uiText(String value,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setTypeface(bold?UI_MEDIUM:UI);t.setLineSpacing(0,1.08f);return t;}
    private TextView brandText(String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setTypeface(BRAND);return t;}
    private LinearLayout panel(int color){LinearLayout p=column();p.setPadding(dp(16),dp(15),dp(16),dp(15));p.setBackground(round(color,14));return p;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private GradientDrawable stroke(int fill,int line,int radius){GradientDrawable d=round(fill,radius);d.setStroke(dp(1),line);return d;}
    private LinearLayout.LayoutParams margins(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(l,t,r,b);return p;}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
