package dev.thefoolish.aidao;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;

import java.util.*;

/** End-to-end generation workspace: brief -> plan -> source -> user-controlled GitHub CI -> APK artifact. */
public class AIDaoActivityV4 extends Activity {
    private static final int BG=Color.rgb(18,19,24),HEADER=Color.rgb(22,23,29),PANEL=Color.rgb(29,31,39),ALT=Color.rgb(35,38,48),MUTED=Color.rgb(157,162,178),BLUE=Color.rgb(80,148,255),GREEN=Color.rgb(76,201,144),YELLOW=Color.rgb(235,190,80),RED=Color.rgb(234,98,108),PURPLE=Color.rgb(145,93,255);
    private static final android.graphics.Typeface UI=android.graphics.Typeface.create("sans-serif",0),BOLD=android.graphics.Typeface.create("sans-serif",1),BRAND=android.graphics.Typeface.create("cursive",1);
    private SharedPreferences prefs; private LinearLayout root,content,bottom; private String project; private int tab=0; private volatile boolean building=false; private String sessionToken="";

    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("aidao_workspace_v4",MODE_PRIVATE);Window w=getWindow();w.setStatusBarColor(BG);w.setNavigationBarColor(Color.rgb(12,13,17));w.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);if(Build.VERSION.SDK_INT>=30)w.setDecorFitsSystemWindows(false);showProjects();}

    private void shell(String title,String sub){root=col();root.setBackgroundColor(BG);LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(18),dp(28),dp(18),dp(14));h.setBackgroundColor(HEADER);TextView logo=text("A",22,Color.WHITE,true);logo.setTypeface(BRAND);logo.setGravity(Gravity.CENTER);logo.setBackground(gradient());h.addView(logo,lp(dp(44),dp(44),0,0,dp(12),0));LinearLayout names=col();names.addView(text(title,20,Color.WHITE,true));names.addView(text(sub,12,MUTED,false));h.addView(names,new LinearLayout.LayoutParams(0,-2,1));h.addView(text("●",16,GREEN,true));root.addView(h);ScrollView s=new ScrollView(this);s.setFillViewport(true);content=col();content.setPadding(dp(18),dp(18),dp(18),dp(30));s.addView(content);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));bottom=nav();root.addView(bottom);setContentView(root);insets(h);}
    private void insets(LinearLayout h){if(Build.VERSION.SDK_INT<23)return;root.setOnApplyWindowInsetsListener((v,i)->{int top=i.getSystemWindowInsetTop(),bot=i.getSystemWindowInsetBottom();if(Build.VERSION.SDK_INT>=30){top=i.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout()).top;bot=i.getInsets(WindowInsets.Type.systemBars()).bottom;boolean ime=i.isVisible(WindowInsets.Type.ime());bottom.setVisibility(ime?View.GONE:View.VISIBLE);}h.setPadding(dp(18),top+dp(22),dp(18),dp(14));bottom.setPadding(dp(6),dp(6),dp(6),Math.max(dp(8),bot+dp(6)));return i;});root.requestApplyInsets();}

    private void showProjects(){project=null;shell("AIDao","Developer workspace");card("BUILD WITH AIDAO","Describe an Android app. AIDao can now plan it, generate a real source tree, and send that generated project to GitHub CI only when you explicitly authorize the send/build step.",BLUE);Button n=primary("New Project");n.setOnClickListener(v->newProject());content.addView(n,lp(-1,dp(50),0,dp(12),0,dp(18)));String p=prefs.getString("project_name",null);if(p!=null){View saved=card("Saved project",p+" · "+stateLabel(),GREEN);saved.setOnClickListener(v->{project=p;tab=0;workspace();});saved.setClickable(true);} }
    private void newProject(){EditText e=new EditText(this);e.setHint("Example: Create an anime app like Mihon with repository-based providers, watch history, favorites, and playback.");e.setMinLines(5);e.setTextSize(14);new AlertDialog.Builder(this).setTitle("Create Android project").setMessage("Describe what you want in ordinary language.").setView(e).setPositiveButton("Create",(d,w)->{String brief=e.getText().toString().trim();if(brief.isEmpty())return;project=titleFrom(brief);prefs.edit().clear().putString("project_name",project).putString("brief",brief).putString("stage","BRIEF READY").apply();workspace();}).setNegativeButton("Cancel",null).show();}

    private void workspace(){if(project==null)project=prefs.getString("project_name","Project");shell(project,"Project workspace · "+stateLabel());tabs();if(tab==0)plan();else if(tab==1)tasks();else if(tab==2)files();else if(tab==3)builds();else github();}
    private void tabs(){HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout r=row();String[] a={"Plan","Tasks","Files","Builds","GitHub"};for(int i=0;i<a.length;i++){final int x=i;TextView t=text(a[i],13,i==tab?Color.WHITE:MUTED,i==tab);t.setGravity(Gravity.CENTER);t.setPadding(dp(16),dp(12),dp(16),dp(12));t.setBackground(round(i==tab?Color.rgb(71,78,104):PANEL,12));t.setOnClickListener(v->{tab=x;workspace();});r.addView(t,lp(-2,-2,0,0,dp(8),0));}hs.addView(r);content.addView(hs,lp(-1,-2,0,0,0,dp(20)));}

    private void plan(){heading("Project plan");card("Project brief",prefs.getString("brief",""),BLUE);if(!prefs.contains("requirements")){Button b=primary("Generate Plan & Tasks");b.setOnClickListener(v->generatePlan());content.addView(b,lp(-1,dp(50),0,dp(12),0,0));return;}label("REQUIREMENTS",BLUE);for(String r:decode(prefs.getString("requirements","")))card("Requirement",r,BLUE);label("ASSUMPTIONS & SAFETY",YELLOW);for(String a:decode(prefs.getString("assumptions","")))card("Assumption",a,YELLOW);}
    private void generatePlan(){ProjectPlanner.Plan p=ProjectPlanner.build(prefs.getString("brief",""),prefs.getString("context",""));SharedPreferences.Editor e=prefs.edit().putString("requirements",encode(p.requirements)).putString("tasks",encode(p.tasks)).putString("assumptions",encode(p.assumptions)).putString("stage","PLAN READY");for(int i=0;i<50;i++)e.remove("task_"+i);for(int i=0;i<p.tasks.size();i++)e.putString("task_"+i,TaskExecutionState.PLANNED.name());e.apply();workspace();}

    private void tasks(){heading("Implementation tasks");List<String> ts=decode(prefs.getString("tasks",""));if(ts.isEmpty()){card("No tasks yet","Generate the project plan first.",MUTED);return;}int c=0,a=0,b=0;for(int i=0;i<ts.size();i++){TaskExecutionState s=task(i);if(s==TaskExecutionState.COMPLETE)c++;else if(s==TaskExecutionState.BLOCKED)b++;else if(s==TaskExecutionState.IN_PROGRESS||s==TaskExecutionState.VERIFYING)a++;}card("AIDao execution state",c+" complete · "+a+" active · "+b+" blocked · "+(ts.size()-c-a-b)+" planned",c==ts.size()?GREEN:BLUE);for(int i=0;i<ts.size();i++){TaskExecutionState s=task(i);card(s.label,ts.get(i),color(s));}content.addView(text("Task states are derived from source generation, verification, CI, and repair signals. They are not manual checkboxes.",12,MUTED,false),lp(-1,-2,0,dp(8),0,0));}

    private void files(){heading("Generated project files");if(!prefs.getBoolean("generated",false)){card("Source not generated","Open Builds and run local source generation after planning.",YELLOW);return;}GeneratedProject g=regenerate();card("Package",g.packageName,GREEN);for(GeneratedProject.FileEntry f:g.files)card(f.path,f.taskHint,BLUE);label("LOCAL VERIFICATION",GREEN);for(String n:g.verificationNotes)card(n.startsWith("PASS")?"Verified":"Problem",n,n.startsWith("PASS")?GREEN:RED);}

    private void builds(){heading("Build pipeline");boolean planned=prefs.contains("tasks"),gen=prefs.getBoolean("generated",false);String ci=prefs.getString("ci_state","Not sent");card("1 · Project context","Complete",GREEN);card("2 · Structured plan",planned?"Ready":"Waiting",planned?GREEN:MUTED);card("3 · Source generation",gen?"Generated & locally verified":"Waiting",gen?GREEN:YELLOW);card("4 · GitHub Android CI",ci,colorForState(ci));if(!planned)return;if(!gen){Button g=primary("Generate Real Android Source");g.setOnClickListener(v->generateSource());content.addView(g,lp(-1,dp(50),0,dp(12),0,0));}else{Button gh=primary("Configure GitHub & Build");gh.setOnClickListener(v->{tab=4;workspace();});content.addView(gh,lp(-1,dp(50),0,dp(12),0,0));}String url=prefs.getString("run_url",null);if(url!=null){Button open=secondary("Open CI Run / APK Artifact");open.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(url))));content.addView(open,lp(-1,dp(50),0,dp(10),0,0));}}
    private void generateSource(){List<String> ts=decode(prefs.getString("tasks",""));setAll(ts,TaskExecutionState.IN_PROGRESS);GeneratedProject g=regenerate();boolean ok=true;for(String n:g.verificationNotes)if(n.startsWith("FAIL"))ok=false;if(ok){setAll(ts,TaskExecutionState.VERIFYING);SharedPreferences.Editor e=prefs.edit().putBoolean("generated",true).putString("stage","SOURCE READY");for(int i=0;i<Math.min(ts.size(),Math.max(1,ts.size()-1));i++)e.putString("task_"+i,TaskExecutionState.COMPLETE.name());if(!ts.isEmpty())e.putString("task_"+(ts.size()-1),TaskExecutionState.VERIFYING.name());e.apply();}else{prefs.edit().putString("stage","SOURCE BLOCKED").apply();setAll(ts,TaskExecutionState.BLOCKED);}workspace();}

    private void github(){heading("GitHub build connection");if(!prefs.getBoolean("generated",false)){card("Generated source required","Generate and verify the local Android source tree before sending anything to GitHub.",YELLOW);return;}EditText repo=input("owner/repository",prefs.getString("repo","IcyKokane/AIDaoPublic"));EditText token=input("Fine-grained GitHub token (not saved)","");token.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);content.addView(repo);content.addView(token,lp(-1,-2,0,dp(8),0,0));content.addView(text("AIDao never stores the token. This explicit action creates an isolated generated-project branch; it does not modify the repository default branch. The token needs repository Contents and Workflows/Actions permissions sufficient to create the generated branch and workflow.",12,MUTED,false),lp(-1,-2,0,dp(8),0,dp(10)));if(building)card("Build running",prefs.getString("ci_state","Working…"),PURPLE);Button send=primary(building?"Build in progress…":"Send Generated Source & Build");send.setEnabled(!building);send.setOnClickListener(v->{String r=repo.getText().toString().trim(),t=token.getText().toString();if(r.isEmpty()||t.isEmpty()){Toast.makeText(this,"Repository and session token are required",Toast.LENGTH_SHORT).show();return;}prefs.edit().putString("repo",r).apply();sessionToken=t;startRemoteBuild(r,t);});content.addView(send,lp(-1,dp(52),0,dp(12),0,0));String run=prefs.getString("run_url",null);if(run!=null){Button open=secondary("Open Latest CI Run");open.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(run))));content.addView(open,lp(-1,dp(50),0,dp(10),0,0));}}

    private void startRemoteBuild(String repo,String token){building=true;updateCi("Preparing generated branch");new Thread(()->{try{GitHubGeneratedBuildClient client=new GitHubGeneratedBuildClient();GeneratedProject g=regenerate();GitHubGeneratedBuildClient.BuildReceipt r=client.sendBuildAndWait(repo,token,g,(stage,detail)->{prefs.edit().putString("ci_state",stage+" · "+detail).apply();runOnUiThread(()->{if(tab==4)workspace();});});if(!r.success()){prefs.edit().putString("ci_state","CI failed · bounded repair starting").putString("run_url",r.runUrl).putString("repair",GitHubGeneratedBuildClient.boundedRepairHint(r.failureSummary)).apply();GeneratedProjectRepairer.RepairResult fix=new GeneratedProjectRepairer().repair(g,r.failureSummary);prefs.edit().putString("repair",fix.action).apply();GitHubGeneratedBuildClient.BuildReceipt retry=client.sendBuildAndWait(repo,token,fix.project,(s,d)->prefs.edit().putString("ci_state","Repair rebuild · "+s+" · "+d).apply());finishReceipt(retry);}else finishReceipt(r);}catch(Exception ex){prefs.edit().putString("ci_state","Blocked · "+safe(ex.getMessage())).putString("stage","BUILD BLOCKED").apply();setLast(TaskExecutionState.BLOCKED);}finally{sessionToken="";building=false;runOnUiThread(()->workspace());}}).start();}
    private void finishReceipt(GitHubGeneratedBuildClient.BuildReceipt r){if(r.success()){prefs.edit().putString("ci_state","Successful · APK artifact: "+r.artifactName).putString("run_url",r.runUrl).putString("stage","APK READY").putString("branch",r.branch).apply();setAll(decode(prefs.getString("tasks","")),TaskExecutionState.COMPLETE);}else{prefs.edit().putString("ci_state","Blocked after bounded repair · "+safe(r.failureSummary)).putString("run_url",r.runUrl).putString("stage","BUILD BLOCKED").apply();setLast(TaskExecutionState.BLOCKED);}}

    private GeneratedProject regenerate(){return new LocalSourceGenerator().generate(project,prefs.getString("brief",""),decode(prefs.getString("requirements","")),decode(prefs.getString("tasks","")));}
    private TaskExecutionState task(int i){return TaskExecutionState.fromStored(prefs.getString("task_"+i,TaskExecutionState.PLANNED.name()));}
    private void setAll(List<String> t,TaskExecutionState s){SharedPreferences.Editor e=prefs.edit();for(int i=0;i<t.size();i++)e.putString("task_"+i,s.name());e.apply();}
    private void setLast(TaskExecutionState s){List<String> t=decode(prefs.getString("tasks",""));if(!t.isEmpty())prefs.edit().putString("task_"+(t.size()-1),s.name()).apply();}
    private void updateCi(String s){prefs.edit().putString("ci_state",s).apply();}

    private LinearLayout nav(){LinearLayout n=row();n.setBackgroundColor(Color.rgb(13,14,18));String[] a={"Projects","AIDao","Activity","Settings"};for(int i=0;i<a.length;i++){final int x=i;TextView v=text(a[i],11,i==1?Color.WHITE:MUTED,i==1);v.setGravity(Gravity.CENTER);v.setMinHeight(dp(58));v.setOnClickListener(q->{if(x==0)showProjects();else if(x==1){project=prefs.getString("project_name",null);if(project==null)showProjects();else workspace();}else Toast.makeText(this,a[x]+" remains available in the full workspace shell.",Toast.LENGTH_SHORT).show();});n.addView(v,new LinearLayout.LayoutParams(0,-2,1));}return n;}
    private void heading(String s){content.addView(text(s,21,Color.WHITE,true),lp(-1,-2,0,0,0,dp(10)));}private void label(String s,int c){content.addView(text(s,11,c,true),lp(-1,-2,0,dp(16),0,dp(6)));}
    private View card(String title,String detail,int color){LinearLayout p=col();p.setPadding(dp(16),dp(15),dp(16),dp(15));p.setBackground(round(PANEL,14));LinearLayout r=row();TextView dot=text("◆",14,color,true);r.addView(dot,lp(dp(34),-2,0,0,dp(8),0));LinearLayout l=col();l.addView(text(title,14,Color.WHITE,true));l.addView(text(detail,12,MUTED,false));r.addView(l,new LinearLayout.LayoutParams(0,-2,1));p.addView(r);content.addView(p,lp(-1,-2,0,0,0,dp(8)));return p;}
    private EditText input(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(MUTED);e.setTextColor(Color.WHITE);e.setText(value);e.setTextSize(14);e.setSingleLine(true);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackground(round(PANEL,12));return e;}
    private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTypeface(BOLD);b.setBackground(round(Color.rgb(83,91,242),12));return b;}private Button secondary(String s){Button b=primary(s);b.setBackground(stroke(PANEL,Color.rgb(73,78,94),12));return b;}
    private TextView text(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setTypeface(bold?BOLD:UI);t.setLineSpacing(0,1.08f);return t;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private GradientDrawable round(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}private GradientDrawable stroke(int c,int line,int r){GradientDrawable d=round(c,r);d.setStroke(dp(1),line);return d;}private GradientDrawable gradient(){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{BLUE,PURPLE});d.setCornerRadius(dp(13));return d;}
    private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(l,t,r,b);return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private int color(TaskExecutionState s){if(s==TaskExecutionState.COMPLETE)return GREEN;if(s==TaskExecutionState.BLOCKED)return RED;if(s==TaskExecutionState.VERIFYING)return PURPLE;if(s==TaskExecutionState.IN_PROGRESS)return BLUE;return MUTED;}private int colorForState(String s){String x=s.toLowerCase();if(x.contains("success")||x.contains("apk"))return GREEN;if(x.contains("blocked")||x.contains("fail"))return RED;if(x.contains("waiting")||x.contains("not sent"))return MUTED;return BLUE;}
    private String stateLabel(){return prefs.getString("stage","BRIEF READY");}private String safe(String s){return s==null?"Unknown error":s.substring(0,Math.min(180,s.length()));}
    private String titleFrom(String brief){String[] w=brief.trim().split("\\s+");StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(5,w.length);i++){String x=w[i].replaceAll("[^A-Za-z0-9'-]","");if(x.isEmpty())continue;if(b.length()>0)b.append(' ');b.append(Character.toUpperCase(x.charAt(0))).append(x.substring(1));}return b.length()==0?"New Android App":b.toString();}
    private String encode(List<String> v){StringBuilder b=new StringBuilder();for(String s:v){if(b.length()>0)b.append("\n---ITEM---\n");b.append(s.replace("\n"," "));}return b.toString();}private List<String> decode(String raw){List<String> o=new ArrayList<>();if(raw==null||raw.trim().isEmpty())return o;for(String s:raw.split("\\n---ITEM---\\n"))if(!s.trim().isEmpty())o.add(s.trim());return o;}
}
