package dev.thefoolish.aidao;

import java.util.ArrayList;
import java.util.List;

/**
 * Turns deterministic non-media scaffolds into coherent offline-first Android products.
 * Unsupported external capabilities are described honestly instead of being represented
 * by sample buttons or fabricated completion.
 */
final class GeneralProductPostProcessor {
    private enum Domain { FINANCE, TRACKER, CONTENT, SOCIAL, COMMERCE, NONE }

    static final class Result {
        final String projectName, packageName;
        final List<GeneratedProject.FileEntry> files;
        final List<String> notes;
        Result(String projectName,String packageName,List<GeneratedProject.FileEntry> files,List<String> notes){
            this.projectName=projectName;this.packageName=packageName;this.files=files;this.notes=notes;
        }
    }

    static Result process(String projectName,String packageName,List<GeneratedProject.FileEntry> incoming){
        List<GeneratedProject.FileEntry> source=incoming==null?new ArrayList<>():new ArrayList<>(incoming);
        Domain domain=detect(source);
        if(domain==Domain.NONE)return new Result(projectName,packageName,source,new ArrayList<>());
        String javaPath=packageName.replace('.','/');
        List<GeneratedProject.FileEntry> out=new ArrayList<>();
        for(GeneratedProject.FileEntry f:source){
            if(f==null)continue;
            if(f.path.endsWith("/GeneratedScreen.java")||f.path.endsWith("/AppScreen.java")||replaced(f.path,domain))continue;
            out.add(f);
        }
        add(out,javaPath,"AppScreen.java",appScreen(packageName,projectName),"Use inset-aware Android product chrome and accessible navigation");
        switch(domain){
            case FINANCE:
                add(out,javaPath,"MainActivity.java",financeMain(packageName),"Show persisted finance summary");
                add(out,javaPath,"TransactionsActivity.java",financeTransactions(packageName),"Persist validated transaction records");
                add(out,javaPath,"BudgetsActivity.java",financeBudget(packageName),"Persist monthly budget");
                add(out,javaPath,"ReportsActivity.java",financeReports(packageName),"Calculate finance report");
                break;
            case TRACKER:
                add(out,javaPath,"MainActivity.java",trackerMain(packageName),"Show persisted activity summary");
                add(out,javaPath,"TimelineActivity.java",trackerTimeline(packageName),"Persist activity records");
                add(out,javaPath,"ReportsActivity.java",trackerReports(packageName),"Calculate activity report");
                add(out,javaPath,"DataControlsActivity.java",trackerControls(packageName),"Provide explicit local data controls");
                break;
            case CONTENT:
                add(out,javaPath,"MainActivity.java",contentMain(packageName),"Show writing workspace");
                add(out,javaPath,"EditorActivity.java",contentEditor(packageName),"Persist documents and recover drafts");
                add(out,javaPath,"SearchActivity.java",contentSearch(packageName),"Search local documents");
                add(out,javaPath,"LibraryActivity.java",contentLibrary(packageName),"Browse local documents");
                break;
            case SOCIAL:
                add(out,javaPath,"MainActivity.java",socialMain(packageName),"Show private local community summary");
                add(out,javaPath,"InboxActivity.java",socialInbox(packageName),"Persist local message drafts/history without pretending remote delivery");
                add(out,javaPath,"ProfileActivity.java",socialProfile(packageName),"Persist and validate profile fields");
                add(out,javaPath,"SettingsActivity.java",socialSettings(packageName),"Expose explicit local-data controls and capability boundaries");
                break;
            case COMMERCE:
                add(out,javaPath,"MainActivity.java",commerceMain(packageName),"Persist a local product catalog");
                add(out,javaPath,"ProductActivity.java",commerceProducts(packageName),"Add validated products and cart items");
                add(out,javaPath,"CartActivity.java",commerceCart(packageName),"Review cart and require explicit order confirmation");
                add(out,javaPath,"OrdersActivity.java",commerceOrders(packageName),"Persist local order history without claiming payment processing");
                break;
            default: break;
        }
        List<String> notes=new ArrayList<>();
        notes.add("PASS non-media product pass replaced generic sample-state surfaces for "+domain.name().toLowerCase());
        notes.add("PASS generated product uses inset-aware Android chrome and >=48dp interactive targets");
        notes.add("PASS domain records persist in SharedPreferences across process/activity restart");
        notes.add("PASS user input has domain-specific validation and actionable inline errors");
        if(domain==Domain.CONTENT)notes.add("PASS editor recovers an in-progress draft after lifecycle interruption");
        if(domain==Domain.SOCIAL)notes.add("PASS social product distinguishes local drafts/history from unavailable remote delivery");
        if(domain==Domain.COMMERCE)notes.add("PASS commerce product keeps local order intent separate from payment/spending");
        return new Result(projectName,packageName,out,notes);
    }

    private static Domain detect(List<GeneratedProject.FileEntry> files){
        if(has(files,"/MediaProvider.java"))return Domain.NONE;
        if(has(files,"/TransactionsActivity.java")&&has(files,"/BudgetsActivity.java"))return Domain.FINANCE;
        if(has(files,"/TimelineActivity.java")&&has(files,"/DataControlsActivity.java"))return Domain.TRACKER;
        if(has(files,"/EditorActivity.java")&&has(files,"/SearchActivity.java"))return Domain.CONTENT;
        if(has(files,"/InboxActivity.java")&&has(files,"/ProfileActivity.java")&&has(files,"/SettingsActivity.java"))return Domain.SOCIAL;
        if(has(files,"/ProductActivity.java")&&has(files,"/CartActivity.java")&&has(files,"/OrdersActivity.java"))return Domain.COMMERCE;
        return Domain.NONE;
    }
    private static boolean has(List<GeneratedProject.FileEntry> files,String suffix){for(GeneratedProject.FileEntry f:files)if(f!=null&&f.path!=null&&f.path.endsWith(suffix))return true;return false;}
    private static boolean replaced(String path,Domain d){
        if(path==null)return false;if(path.endsWith("/MainActivity.java"))return true;
        switch(d){
            case FINANCE:return path.endsWith("/TransactionsActivity.java")||path.endsWith("/BudgetsActivity.java")||path.endsWith("/ReportsActivity.java");
            case TRACKER:return path.endsWith("/TimelineActivity.java")||path.endsWith("/ReportsActivity.java")||path.endsWith("/DataControlsActivity.java");
            case CONTENT:return path.endsWith("/EditorActivity.java")||path.endsWith("/SearchActivity.java")||path.endsWith("/LibraryActivity.java");
            case SOCIAL:return path.endsWith("/InboxActivity.java")||path.endsWith("/ProfileActivity.java")||path.endsWith("/SettingsActivity.java");
            case COMMERCE:return path.endsWith("/ProductActivity.java")||path.endsWith("/CartActivity.java")||path.endsWith("/OrdersActivity.java");
            default:return false;
        }
    }
    private static void add(List<GeneratedProject.FileEntry> out,String path,String name,String content,String hint){out.add(new GeneratedProject.FileEntry("app/src/main/java/"+path+"/"+name,content,hint));}
    private static String pkg(String p,String body){return "package "+p+";"+body;}

    private static String appScreen(String p,String appName){return pkg(p,
        "import android.app.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;"+
        "public abstract class AppScreen extends Activity{"+
        "protected LinearLayout body;protected LocalStore store;private TextView topTitle;private LinearLayout bottomNav;protected final int BG=Color.rgb(15,17,22),SURFACE=Color.rgb(27,30,38),SURFACE2=Color.rgb(36,40,50),TEXT=Color.rgb(238,240,246),MUTED=Color.rgb(164,171,187);"+
        "@Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);store=new LocalStore(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.VERTICAL);bar.setPadding(dp(20),dp(12),dp(20),dp(10));TextView brand=text(\""+java(appName)+"\",12,false);brand.setTextColor(MUTED);bar.addView(brand);topTitle=text(\"Home\",24,true);bar.addView(topTitle);root.addView(bar,new LinearLayout.LayoutParams(-1,-2));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(8),dp(16),dp(24));scroll.addView(body,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));bottomNav=new LinearLayout(this);bottomNav.setOrientation(LinearLayout.HORIZONTAL);bottomNav.setBackgroundColor(SURFACE);root.addView(bottomNav,new LinearLayout.LayoutParams(-1,-2));setContentView(root);if(Build.VERSION.SDK_INT>=21){root.setOnApplyWindowInsetsListener((v,i)->{bar.setPadding(dp(20),i.getSystemWindowInsetTop()+dp(10),dp(20),dp(10));bottomNav.setPadding(dp(6),dp(6),dp(6),i.getSystemWindowInsetBottom()+dp(6));return i;});root.requestApplyInsets();}render();}"+
        "protected abstract void render();protected void title(String s){topTitle.setText(s);}protected void subtitle(String s){TextView t=text(s,14,false);t.setTextColor(MUTED);body.addView(t,margin(-1,-2,0,0,0,12));}protected void section(String s){body.addView(text(s,18,true),margin(-1,-2,0,10,0,8));}"+
        "protected TextView text(String v,int size,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextColor(TEXT);t.setTextSize(size);t.setTypeface(android.graphics.Typeface.create(\"sans-serif\",bold?1:0));t.setGravity(Gravity.CENTER_VERTICAL);return t;}"+
        "protected EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setPadding(dp(14),0,dp(14),0);e.setBackground(round(SURFACE,14));e.setMinHeight(dp(52));e.setContentDescription(hint);return e;}"+
        "protected Button button(String label){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextColor(TEXT);b.setMinHeight(dp(48));b.setContentDescription(label);b.setBackground(round(SURFACE2,14));b.setLayoutParams(margin(-1,dp(50),0,6,0,6));return b;}"+
        "protected LinearLayout card(String h,String s){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(round(SURFACE,16));c.addView(text(h,16,true));if(s!=null&&!s.isEmpty()){TextView t=text(s,13,false);t.setTextColor(MUTED);c.addView(t);}c.setLayoutParams(margin(-1,-2,0,0,0,10));return c;}"+
        "protected void nav(String[] labels,Class[] screens){bottomNav.removeAllViews();for(int x=0;x<labels.length;x++){final Class target=screens[x];TextView item=text(labels[x],11,false);item.setGravity(Gravity.CENTER);item.setMinHeight(dp(52));item.setContentDescription(\"Open \"+labels[x]);item.setOnClickListener(v->AppNavigator.open(this,target));bottomNav.addView(item,new LinearLayout.LayoutParams(0,dp(52),1));}}"+
        "protected GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}protected LinearLayout.LayoutParams margin(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(w,h);q.setMargins(dp(l),dp(t),dp(r),dp(b));return q;}protected int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}}"
    );}

    private static String financeMain(String p){return pkg(p,"public final class MainActivity extends AppScreen{protected void render(){title(\"Overview\");subtitle(\"Your local finance snapshot. Data stays on this device.\");int spent=total(),budget=store.number(\"monthly_budget_cents\");body.addView(card(\"Spent\",money(spent)));body.addView(card(\"Monthly budget\",budget>0?money(budget):\"Not set\"));body.addView(card(\"Remaining\",budget>0?money(budget-spent):\"Set a budget to calculate\"));nav(new String[]{\"Overview\",\"Transactions\",\"Budget\",\"Reports\"},new Class[]{MainActivity.class,TransactionsActivity.class,BudgetsActivity.class,ReportsActivity.class});}private int total(){int s=0;for(String r:store.text(\"transactions\",\"\").split(\"\\n\")){if(r.isEmpty())continue;String[] x=r.split(\"[|]\",3);try{s+=Integer.parseInt(x[0]);}catch(Exception ignored){}}return s;}private String money(int c){return \"$\"+(c/100)+\".\"+String.format(java.util.Locale.US,\"%02d\",Math.abs(c%100));}}");}
    private static String financeTransactions(String p){return pkg(p,"import android.text.InputType;import android.widget.*;public final class TransactionsActivity extends AppScreen{private LinearLayout list;protected void render(){title(\"Transactions\");subtitle(\"Add an expense. Amount, category, and note are persisted locally.\");EditText amount=field(\"Amount, e.g. 12.50\");amount.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText category=field(\"Category\");EditText note=field(\"Note (optional)\");body.addView(amount);body.addView(category);body.addView(note);Button add=button(\"Add transaction\");body.addView(add);section(\"Recent\");list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);add.setOnClickListener(v->{String a=amount.getText().toString().trim(),c=category.getText().toString().trim();if(a.isEmpty()){amount.setError(\"Enter an amount\");return;}if(c.isEmpty()){category.setError(\"Enter a category\");return;}try{int cents=(int)Math.round(Double.parseDouble(a)*100);if(cents<=0){amount.setError(\"Amount must be greater than zero\");return;}String old=store.text(\"transactions\",\"\");store.putText(\"transactions\",cents+\"|\"+clean(c)+\"|\"+clean(note.getText().toString())+(old.isEmpty()?\"\":\"\\n\"+old));amount.setText(\"\");note.setText(\"\");show();}catch(Exception e){amount.setError(\"Use a valid number\");}});show();nav(new String[]{\"Overview\",\"Transactions\",\"Budget\",\"Reports\"},new Class[]{MainActivity.class,TransactionsActivity.class,BudgetsActivity.class,ReportsActivity.class});}private String clean(String s){return s.replace(\"|\",\"/\").replace(\"\\n\",\" \");}private void show(){list.removeAllViews();String raw=store.text(\"transactions\",\"\");if(raw.isEmpty()){list.addView(text(\"No transactions yet.\",14,false));return;}int n=0;for(String r:raw.split(\"\\n\")){String[] x=r.split(\"[|]\",3);if(x.length>=2)list.addView(card(x[1],(x.length==3?x[2]+\" · \":\"\")+x[0]+\" cents\"));if(++n>=30)break;}}}");}
    private static String financeBudget(String p){return pkg(p,"import android.text.InputType;import android.widget.*;public final class BudgetsActivity extends AppScreen{protected void render(){title(\"Budget\");int c=store.number(\"monthly_budget_cents\");subtitle(c>0?\"Current monthly budget: \"+c+\" cents\":\"Set a monthly spending target.\");EditText v=field(\"Monthly budget\");v.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);body.addView(v);Button save=button(\"Save budget\");save.setOnClickListener(x->{try{int cents=(int)Math.round(Double.parseDouble(v.getText().toString().trim())*100);if(cents<=0){v.setError(\"Budget must be greater than zero\");return;}store.number(\"monthly_budget_cents\",cents);recreate();}catch(Exception e){v.setError(\"Use a valid number\");}});body.addView(save);nav(new String[]{\"Overview\",\"Transactions\",\"Budget\",\"Reports\"},new Class[]{MainActivity.class,TransactionsActivity.class,BudgetsActivity.class,ReportsActivity.class});}}");}
    private static String financeReports(String p){return pkg(p,"public final class ReportsActivity extends AppScreen{protected void render(){title(\"Reports\");int count=0,total=0;for(String r:store.text(\"transactions\",\"\").split(\"\\n\")){if(r.isEmpty())continue;try{total+=Integer.parseInt(r.split(\"[|]\",3)[0]);count++;}catch(Exception ignored){}}int budget=store.number(\"monthly_budget_cents\");body.addView(card(\"Transactions\",String.valueOf(count)));body.addView(card(\"Total spent\",total+\" cents\"));if(budget>0)body.addView(card(total<=budget?\"Within budget\":\"Over budget\",(budget-total)+\" cents remaining\"));nav(new String[]{\"Overview\",\"Transactions\",\"Budget\",\"Reports\"},new Class[]{MainActivity.class,TransactionsActivity.class,BudgetsActivity.class,ReportsActivity.class});}}");}

    private static String trackerMain(String p){return pkg(p,"public final class MainActivity extends AppScreen{protected void render(){title(\"Activity\");int count=0,min=0;for(String r:store.text(\"activity_log\",\"\").split(\"\\n\")){if(r.isEmpty())continue;try{min+=Integer.parseInt(r.split(\"[|]\",2)[0]);count++;}catch(Exception ignored){}}body.addView(card(\"Entries\",String.valueOf(count)));body.addView(card(\"Tracked time\",min+\" minutes\"));body.addView(card(\"Privacy\",\"Only activity you explicitly enter is stored.\"));nav(new String[]{\"Activity\",\"Timeline\",\"Reports\",\"Data\"},new Class[]{MainActivity.class,TimelineActivity.class,ReportsActivity.class,DataControlsActivity.class});}}");}
    private static String trackerTimeline(String p){return pkg(p,"import android.text.InputType;import android.widget.*;public final class TimelineActivity extends AppScreen{private LinearLayout list;protected void render(){title(\"Timeline\");EditText name=field(\"Activity name\"),minutes=field(\"Minutes\");minutes.setInputType(InputType.TYPE_CLASS_NUMBER);body.addView(name);body.addView(minutes);Button add=button(\"Add activity\");body.addView(add);section(\"Recent\");list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);add.setOnClickListener(v->{String n=name.getText().toString().trim(),m=minutes.getText().toString().trim();if(n.isEmpty()){name.setError(\"Enter an activity\");return;}try{int value=Integer.parseInt(m);if(value<1||value>1440){minutes.setError(\"Enter 1–1440 minutes\");return;}String old=store.text(\"activity_log\",\"\");store.putText(\"activity_log\",value+\"|\"+n.replace(\"|\",\"/\").replace(\"\\n\",\" \")+(old.isEmpty()?\"\":\"\\n\"+old));name.setText(\"\");minutes.setText(\"\");show();}catch(Exception e){minutes.setError(\"Enter 1–1440 minutes\");}});show();nav(new String[]{\"Activity\",\"Timeline\",\"Reports\",\"Data\"},new Class[]{MainActivity.class,TimelineActivity.class,ReportsActivity.class,DataControlsActivity.class});}private void show(){list.removeAllViews();String raw=store.text(\"activity_log\",\"\");if(raw.isEmpty()){list.addView(text(\"No activity recorded yet.\",14,false));return;}for(String r:raw.split(\"\\n\")){String[] x=r.split(\"[|]\",2);if(x.length==2)list.addView(card(x[1],x[0]+\" minutes\"));}}}");}
    private static String trackerReports(String p){return pkg(p,"public final class ReportsActivity extends AppScreen{protected void render(){title(\"Reports\");int count=0,min=0;for(String r:store.text(\"activity_log\",\"\").split(\"\\n\")){if(r.isEmpty())continue;try{min+=Integer.parseInt(r.split(\"[|]\",2)[0]);count++;}catch(Exception ignored){}}body.addView(card(\"Activities\",String.valueOf(count)));body.addView(card(\"Total time\",min+\" minutes\"));body.addView(card(\"Average\",count==0?\"No entries\":(min/count)+\" minutes per entry\"));nav(new String[]{\"Activity\",\"Timeline\",\"Reports\",\"Data\"},new Class[]{MainActivity.class,TimelineActivity.class,ReportsActivity.class,DataControlsActivity.class});}}");}
    private static String trackerControls(String p){return pkg(p,"import android.widget.*;public final class DataControlsActivity extends AppScreen{private boolean armed=false;protected void render(){title(\"Data controls\");subtitle(\"All manually entered activity is local. Clearing it is explicit and irreversible.\");Button clear=button(\"Clear local activity history\");clear.setOnClickListener(v->{if(!armed){armed=true;clear.setText(\"Tap again to confirm clear\");return;}store.putText(\"activity_log\",\"\");armed=false;clear.setText(\"Cleared\");});body.addView(clear);nav(new String[]{\"Activity\",\"Timeline\",\"Reports\",\"Data\"},new Class[]{MainActivity.class,TimelineActivity.class,ReportsActivity.class,DataControlsActivity.class});}}");}

    private static String contentMain(String p){return pkg(p,"public final class MainActivity extends AppScreen{protected void render(){title(\"Writing\");subtitle(\"Draft locally, recover interrupted work, and save documents explicitly.\");String draft=store.text(\"draft_body\",\"\");body.addView(card(\"Draft recovery\",draft.isEmpty()?\"No unfinished draft\":\"An unfinished draft is available\"));body.addView(card(\"Saved documents\",String.valueOf(count())));nav(new String[]{\"Writing\",\"Editor\",\"Search\",\"Library\"},new Class[]{MainActivity.class,EditorActivity.class,SearchActivity.class,LibraryActivity.class});}private int count(){String s=store.text(\"documents\",\"\");return s.isEmpty()?0:s.split(\"\\n\").length;}}");}
    private static String contentEditor(String p){return pkg(p,"import android.widget.*;public final class EditorActivity extends AppScreen{private EditText titleField,bodyField;protected void render(){title(\"Editor\");titleField=field(\"Document title\");titleField.setText(store.text(\"draft_title\",\"\"));bodyField=new EditText(this);bodyField.setHint(\"Write here…\");bodyField.setText(store.text(\"draft_body\",\"\"));bodyField.setTextColor(TEXT);bodyField.setHintTextColor(MUTED);bodyField.setGravity(android.view.Gravity.TOP);bodyField.setMinHeight(dp(220));body.addView(titleField);body.addView(bodyField);Button save=button(\"Save document\");save.setOnClickListener(v->{String t=titleField.getText().toString().trim(),b=bodyField.getText().toString().trim();if(t.isEmpty()){titleField.setError(\"Enter a title\");return;}if(b.isEmpty()){bodyField.setError(\"Write some content before saving\");return;}String row=clean(t)+\"|\"+clean(b);String old=store.text(\"documents\",\"\");store.putText(\"documents\",row+(old.isEmpty()?\"\":\"\\n\"+old));store.putText(\"draft_title\",\"\");store.putText(\"draft_body\",\"\");titleField.setText(\"\");bodyField.setText(\"\");});body.addView(save);nav(new String[]{\"Writing\",\"Editor\",\"Search\",\"Library\"},new Class[]{MainActivity.class,EditorActivity.class,SearchActivity.class,LibraryActivity.class});}protected void onPause(){super.onPause();if(titleField!=null)store.putText(\"draft_title\",titleField.getText().toString());if(bodyField!=null)store.putText(\"draft_body\",bodyField.getText().toString());}private String clean(String s){return s.replace(\"|\",\"/\").replace(\"\\n\",\" ↵ \");}}");}
    private static String contentSearch(String p){return pkg(p,"import android.widget.*;public final class SearchActivity extends AppScreen{private LinearLayout list;protected void render(){title(\"Search\");EditText q=field(\"Search documents\");body.addView(q);Button go=button(\"Search documents\");body.addView(go);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);go.setOnClickListener(v->show(q.getText().toString()));show(\"\");nav(new String[]{\"Writing\",\"Editor\",\"Search\",\"Library\"},new Class[]{MainActivity.class,EditorActivity.class,SearchActivity.class,LibraryActivity.class});}private void show(String q){list.removeAllViews();String term=q==null?\"\":q.trim().toLowerCase(java.util.Locale.US);String raw=store.text(\"documents\",\"\");if(raw.isEmpty()){list.addView(text(\"No saved documents.\",14,false));return;}int found=0;for(String r:raw.split(\"\\n\")){String[] x=r.split(\"[|]\",2);if(x.length==2&&(term.isEmpty()||r.toLowerCase(java.util.Locale.US).contains(term))){list.addView(card(x[0],x[1]));found++;}}if(found==0)list.addView(text(\"No documents match your search.\",14,false));}}");}
    private static String contentLibrary(String p){return pkg(p,"public final class LibraryActivity extends AppScreen{protected void render(){title(\"Library\");String raw=store.text(\"documents\",\"\");if(raw.isEmpty())body.addView(text(\"No saved documents yet.\",14,false));else for(String r:raw.split(\"\\n\")){String[] x=r.split(\"[|]\",2);if(x.length==2)body.addView(card(x[0],x[1]));}nav(new String[]{\"Writing\",\"Editor\",\"Search\",\"Library\"},new Class[]{MainActivity.class,EditorActivity.class,SearchActivity.class,LibraryActivity.class});}}");}

    private static String socialMain(String p){return pkg(p,"public final class MainActivity extends AppScreen{protected void render(){title(\"Community\");String name=store.text(\"profile_name\",\"\");String log=store.text(\"message_log\",\"\");body.addView(card(\"Profile\",name.isEmpty()?\"Not configured\":name));body.addView(card(\"Local messages\",log.isEmpty()?\"No drafts/history yet\":String.valueOf(log.split(\"\\n\").length)));body.addView(card(\"Connectivity\",\"No remote delivery backend is configured. Messages remain local unless a real backend is explicitly integrated.\"));nav(new String[]{\"Home\",\"Inbox\",\"Profile\",\"Settings\"},new Class[]{MainActivity.class,InboxActivity.class,ProfileActivity.class,SettingsActivity.class});}}");}
    private static String socialInbox(String p){return pkg(p,"import android.widget.*;public final class InboxActivity extends AppScreen{private LinearLayout list;protected void render(){title(\"Inbox\");subtitle(\"Local draft/history workspace. No remote delivery backend is configured.\");EditText who=field(\"Recipient or contact\"),message=field(\"Message\");body.addView(who);body.addView(message);Button add=button(\"Add local message\");body.addView(add);section(\"Local history\");list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);add.setOnClickListener(v->{String w=who.getText().toString().trim(),m=message.getText().toString().trim();if(w.isEmpty()){who.setError(\"Enter a recipient or contact\");return;}if(m.isEmpty()){message.setError(\"Enter a message\");return;}String old=store.text(\"message_log\",\"\");store.putText(\"message_log\",clean(w)+\"|\"+clean(m)+(old.isEmpty()?\"\":\"\\n\"+old));message.setText(\"\");show();});show();nav(new String[]{\"Home\",\"Inbox\",\"Profile\",\"Settings\"},new Class[]{MainActivity.class,InboxActivity.class,ProfileActivity.class,SettingsActivity.class});}private String clean(String s){return s.replace(\"|\",\"/\").replace(\"\\n\",\" \");}private void show(){list.removeAllViews();String raw=store.text(\"message_log\",\"\");if(raw.isEmpty()){list.addView(text(\"No local messages yet.\",14,false));return;}for(String r:raw.split(\"\\n\")){String[] x=r.split(\"[|]\",2);if(x.length==2)list.addView(card(x[0],x[1]));}}}");}
    private static String socialProfile(String p){return pkg(p,"import android.widget.*;public final class ProfileActivity extends AppScreen{protected void render(){title(\"Profile\");EditText name=field(\"Display name\"),bio=field(\"Bio\");name.setText(store.text(\"profile_name\",\"\"));bio.setText(store.text(\"profile_bio\",\"\"));body.addView(name);body.addView(bio);Button save=button(\"Save profile\");save.setOnClickListener(v->{String n=name.getText().toString().trim();if(n.length()<2){name.setError(\"Enter at least 2 characters\");return;}if(n.length()>50){name.setError(\"Keep the name under 50 characters\");return;}store.putText(\"profile_name\",n);store.putText(\"profile_bio\",bio.getText().toString().trim());save.setText(\"Profile saved\");});body.addView(save);nav(new String[]{\"Home\",\"Inbox\",\"Profile\",\"Settings\"},new Class[]{MainActivity.class,InboxActivity.class,ProfileActivity.class,SettingsActivity.class});}}");}
    private static String socialSettings(String p){return pkg(p,"import android.widget.*;public final class SettingsActivity extends AppScreen{private boolean armed=false;protected void render(){title(\"Settings\");body.addView(card(\"Remote messaging\",\"Unavailable until a real backend, authentication, and privacy policy are integrated. AIDao does not fake delivery.\"));Button clear=button(\"Clear local message history\");clear.setOnClickListener(v->{if(!armed){armed=true;clear.setText(\"Tap again to confirm clear\");return;}store.putText(\"message_log\",\"\");armed=false;clear.setText(\"Cleared\");});body.addView(clear);nav(new String[]{\"Home\",\"Inbox\",\"Profile\",\"Settings\"},new Class[]{MainActivity.class,InboxActivity.class,ProfileActivity.class,SettingsActivity.class});}}");}

    private static String commerceMain(String p){return pkg(p,"public final class MainActivity extends AppScreen{protected void render(){title(\"Catalog\");String products=store.text(\"catalog_items\",\"\"),cart=store.text(\"cart_items\",\"\");body.addView(card(\"Products\",products.isEmpty()?\"No products yet\":String.valueOf(products.split(\"\\n\").length)));body.addView(card(\"Cart\",cart.isEmpty()?\"Empty\":String.valueOf(cart.split(\"\\n\").length)+\" item(s)\"));body.addView(card(\"Payment\",\"No payment provider is connected. Local orders do not spend money.\"));nav(new String[]{\"Catalog\",\"Products\",\"Cart\",\"Orders\"},new Class[]{MainActivity.class,ProductActivity.class,CartActivity.class,OrdersActivity.class});}}");}
    private static String commerceProducts(String p){return pkg(p,"import android.text.InputType;import android.widget.*;public final class ProductActivity extends AppScreen{private LinearLayout list;protected void render(){title(\"Products\");EditText name=field(\"Product name\"),price=field(\"Price\");price.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);body.addView(name);body.addView(price);Button add=button(\"Add product\");body.addView(add);section(\"Catalog\");list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);add.setOnClickListener(v->{String n=name.getText().toString().trim(),p=price.getText().toString().trim();if(n.isEmpty()){name.setError(\"Enter a product name\");return;}try{int cents=(int)Math.round(Double.parseDouble(p)*100);if(cents<=0){price.setError(\"Price must be greater than zero\");return;}String old=store.text(\"catalog_items\",\"\");store.putText(\"catalog_items\",cents+\"|\"+clean(n)+(old.isEmpty()?\"\":\"\\n\"+old));name.setText(\"\");price.setText(\"\");show();}catch(Exception e){price.setError(\"Use a valid price\");}});show();nav(new String[]{\"Catalog\",\"Products\",\"Cart\",\"Orders\"},new Class[]{MainActivity.class,ProductActivity.class,CartActivity.class,OrdersActivity.class});}private String clean(String s){return s.replace(\"|\",\"/\").replace(\"\\n\",\" \");}private void show(){list.removeAllViews();String raw=store.text(\"catalog_items\",\"\");if(raw.isEmpty()){list.addView(text(\"No products yet.\",14,false));return;}for(String r:raw.split(\"\\n\")){String[] x=r.split(\"[|]\",2);if(x.length<2)continue;LinearLayout c=card(x[1],x[0]+\" cents\");Button cart=button(\"Add to cart\");final String row=r;cart.setOnClickListener(v->{String old=store.text(\"cart_items\",\"\");store.putText(\"cart_items\",row+(old.isEmpty()?\"\":\"\\n\"+old));cart.setText(\"Added\");});c.addView(cart);list.addView(c);}}}");}
    private static String commerceCart(String p){return pkg(p,"import android.widget.*;public final class CartActivity extends AppScreen{private boolean armed=false;protected void render(){title(\"Cart\");String raw=store.text(\"cart_items\",\"\");int total=0,count=0;if(!raw.isEmpty())for(String r:raw.split(\"\\n\")){String[] x=r.split(\"[|]\",2);if(x.length==2){try{total+=Integer.parseInt(x[0]);count++;}catch(Exception ignored){}body.addView(card(x[1],x[0]+\" cents\"));}}if(count==0)body.addView(text(\"Your cart is empty.\",14,false));body.addView(card(\"Total\",total+\" cents · local only\"));Button order=button(\"Place local test order\");final int value=total;order.setEnabled(count>0);order.setOnClickListener(v->{if(!armed){armed=true;order.setText(\"Tap again to confirm local order\");return;}String old=store.text(\"order_history\",\"\");String row=System.currentTimeMillis()+\"|\"+value+\"|\"+store.text(\"cart_items\",\"\").replace(\"\\n\",\"; \" );store.putText(\"order_history\",row+(old.isEmpty()?\"\":\"\\n\"+old));store.putText(\"cart_items\",\"\");armed=false;recreate();});body.addView(order);subtitle(\"No payment provider is connected; confirming only records a local test order and never spends money.\");nav(new String[]{\"Catalog\",\"Products\",\"Cart\",\"Orders\"},new Class[]{MainActivity.class,ProductActivity.class,CartActivity.class,OrdersActivity.class});}}");}
    private static String commerceOrders(String p){return pkg(p,"public final class OrdersActivity extends AppScreen{protected void render(){title(\"Orders\");subtitle(\"Local order history only. No payment, fulfillment, or merchant backend is connected.\");String raw=store.text(\"order_history\",\"\");if(raw.isEmpty())body.addView(text(\"No local orders yet.\",14,false));else for(String r:raw.split(\"\\n\")){String[] x=r.split(\"[|]\",3);if(x.length>=2)body.addView(card(\"Local order\",x[1]+\" cents\"));}nav(new String[]{\"Catalog\",\"Products\",\"Cart\",\"Orders\"},new Class[]{MainActivity.class,ProductActivity.class,CartActivity.class,OrdersActivity.class});}}");}

    private static String java(String s){return (s==null?"":s).replace("\\","\\\\").replace("\"","\\\"").replace("\r"," ").replace("\n"," ");}
}
